# <center>**PROJET 10 - NETTOYAGE DES DONNÉES**</center>

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 1 - Importation des librairies et chargement des fichiers</h2>
</div>

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">1.1 - Importation des librairies</h3>
</div>

In [1]:
#Importation de la librairie Pandas
import pandas as pd

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">1.2 - Chargement des fichiers</h3>
</div>

In [2]:
#chargement des fichiers
print("⌛ Chargement des fichiers...")
df_pop = pd.read_csv("Population.csv", encoding='utf-8')
df_water = pd.read_csv("BasicAndSafelyManagedDrinkingWaterServices.csv", encoding='utf-8-sig')
df_mortality = pd.read_csv("MortalityRateAttributedToWater.csv", encoding='utf-8-sig')
df_stability = pd.read_csv("PoliticalStability.csv", encoding='utf-8-sig')
df_geo = pd.read_csv("RegionCountry.csv", encoding='utf-8-sig')
print("✅ Fichiers chargés")

⌛ Chargement des fichiers...
✅ Fichiers chargés

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2 - Analyse exploratoire des fichiers</h2>
</div>

In [3]:
#rassemblement des variables au même endroit dans une structure de dictionnaire Python (clé/valeur)
#permet d'automatiser des tâches sur l'ensemble des fichiers d'un seul coup avec un boucle
datasets = {
    "df_pop" : df_pop,
    "df_water"      : df_water,
    "df_mortality"  : df_mortality,
    "df_stability"  : df_stability,
    "df_geo"     : df_geo,
}

In [4]:
#on boucle les valeurs du dictionnaire
#on ne peut pas boucler directement le dictionnaire à cause de .shape, car un dictionnaire n'a pas de dimensions
from src.mes_fonctions import inspector
for name, df in datasets.items():
    title_df = pd.DataFrame([f"=== ANALYSE DU DATAFRAME : {name} ==="], columns=[""])
    styled_title = title_df.style.set_properties(**{
        'font-size': '18px',
        'font-weight': 'bold',
        'text-align': 'left',
        'color': '#000000'
    }).hide(axis='index').hide(axis='columns') # On cache les index et entêtes pour ne garder que le texte
    display(styled_title)
    inspector(df)

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 20914 ; Nb de colonnes: 4

----------------------
Types de données:
Country         object
Granularity     object
Year             int64
Population     float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Country          239
Granularity        5
Year              19
Population     20515
dtype: int64

----------------------
Valeurs manquantes:
Country        0
Granularity    0
Year           0
Population     0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

           Country Granularity  Year  Population
0      Afghanistan       Total  2000   20779.953
1      Afghanistan        Male  2000   10689.508
2      Afghanistan      Female  2000   10090.449
3      Afghanistan       Rural  2000   15657.474
4      Afghanistan       Urban  2000    4436.282
...            ...         ...   ...         ...
20909     Zimbabwe       Total  2018   14438.802
20910     Zimbabwe        Male  2018    6879.119
20911     Zimbabwe      Female  2018    7559.693
20912     Zimbabwe       Rural  2018   11465.748
20913     Zimbabwe       Urban  2018    5447.513

[20914 rows x 4 columns]

##############################################################################

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 10476 ; Nb de colonnes: 5

----------------------
Types de données:
Year                                                             int64
Country                                                         object
Granularity                                                     object
Population using at least basic drinking-water services (%)    float64
Population using safely managed drinking-water services (%)    float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Year                                                             18
Country                                                         194
Granularity                                                       3
Population using at least basic drinking-water services (%)    7704
Population using safely managed drinking-water services (%)    2877
dtype: int64

----------------------
Valeurs manquantes:
Year                                                              0
Country                                                           0
Granularity                                                       0
Population using at least basic drinking-water services (%)    1061
Population using safely managed drinking-water services (%)    7190
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Year,Country,Granularity,Population using at least basic drinking-water services (%),Population using safely managed drinking-water services (%)
0,2000,Afghanistan,Rural,21.61913,NaN
1,2000,Afghanistan,Total,27.77190,NaN
2,2000,Afghanistan,Urban,49.48745,NaN
3,2000,Albania,Rural,81.78472,NaN
4,2000,Albania,Total,87.86662,49.29324
...,...,...,...,...,...
10471,2017,Zambia,Total,59.96376,NaN
10472,2017,Zambia,Urban,83.86312,46.24515
10473,2017,Zimbabwe,Rural,49.80476,NaN
10474,2017,Zimbabwe,Total,64.05123,NaN
10475,2017,Zimbabwe,Urban,93.99767,NaN

##############################################################################

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 549 ; Nb de colonnes: 5

----------------------
Types de données:
Year                                                               int64
Country                                                           object
Granularity                                                       object
Mortality rate attributed to exposure to unsafe WASH services    float64
WASH deaths                                                      float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Year                                                               1
Country                                                          183
Granularity                                                        3
Mortality rate attributed to exposure to unsafe WASH services    548
WASH deaths                                                      183
dtype: int64

----------------------
Valeurs manquantes:
Year                                                               0
Country                                                            0
Granularity                                                        0
Mortality rate attributed to exposure to unsafe WASH services      0
WASH deaths                                                      366
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Year,Country,Granularity,Mortality rate attributed to exposure to unsafe WASH services,WASH deaths
0,2016,Afghanistan,Female,15.31193,NaN
1,2016,Afghanistan,Male,12.61297,NaN
2,2016,Afghanistan,Total,13.92067,4824.353
3,2016,Albania,Female,0.12552,NaN
4,2016,Albania,Male,0.20650,NaN
...,...,...,...,...,...
544,2016,Zambia,Male,36.61913,NaN
545,2016,Zambia,Total,34.91273,5792.504
546,2016,Zimbabwe,Female,22.16388,NaN
547,2016,Zimbabwe,Male,27.06688,NaN
548,2016,Zimbabwe,Total,24.55074,3965.033

##############################################################################

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 3526 ; Nb de colonnes: 4

----------------------
Types de données:
Country                 object
Year                     int64
Political_Stability    float64
Granularity             object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Country                200
Year                    18
Political_Stability    444
Granularity              1
dtype: int64

----------------------
Valeurs manquantes:
Country                0
Year                   0
Political_Stability    0
Granularity            0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

          Country  Year  Political_Stability Granularity
0     Afghanistan  2000                -2.44       Total
1     Afghanistan  2002                -2.04       Total
2     Afghanistan  2003                -2.20       Total
3     Afghanistan  2004                -2.30       Total
4     Afghanistan  2005                -2.07       Total
...           ...   ...                  ...         ...
3521     Zimbabwe  2014                -0.71       Total
3522     Zimbabwe  2015                -0.62       Total
3523     Zimbabwe  2016                -0.62       Total
3524     Zimbabwe  2017                -0.71       Total
3525     Zimbabwe  2018                -0.71       Total

[3526 rows x 4 columns]

##############################################################################

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 194 ; Nb de colonnes: 2

----------------------
Types de données:
REGION (DISPLAY)     object
COUNTRY (DISPLAY)    object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
REGION (DISPLAY)       6
COUNTRY (DISPLAY)    194
dtype: int64

----------------------
Valeurs manquantes:
REGION (DISPLAY)     0
COUNTRY (DISPLAY)    0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

          REGION (DISPLAY)                   COUNTRY (DISPLAY)
0                   Europe                             Albania
1                   Europe                             Andorra
2                   Europe                             Armenia
3          Western Pacific                           Australia
4                   Europe                             Austria
..                     ...                                 ...
189  Eastern Mediterranean                United Arab Emirates
190               Americas  Venezuela (Bolivarian Republic of)
191        Western Pacific                            Viet Nam
192  Eastern Mediterranean                               Yemen
193                 Africa                            Zimbabwe

[194 rows x 2 columns]

##############################################################################

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 3 - Netoyage des données</h2>
</div>

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Nettoyage du fichier 'BasicAndSafelyManagedDrinkingWaterServices.csv'</h3>
</div>

In [5]:
# --- Nettoyage ---
df_water_clean = df_water.copy()
print("📊 --- ÉTAT INITIAL ---")
inspector(df_water_clean)

#Renommage des colonnes
df_water_clean.columns = ['year', 'country', 'granularity', 'basic_pct', 'safely_managed_pct']
display(df_water_clean)

#On garde uniquement Total / Urban / Rural
df_water_clean = df_water_clean[df_water_clean['granularity'].isin(['Total', 'Urban', 'Rural'])]

#Enlève les éléments entre parenthèse dans la colonne 'country' pour que PowerBI reconnaisse les pays
df_water_clean['country'] = df_water_clean['country'].str.replace(r'\s*\(.*\)', '', regex=True)

df_water_clean['country'] = df_water_clean['country'].replace('Congo', 'Republic of Congo')

#Pivot : une ligne par pays/année, colonnes par granularité
df_water_pivot = df_water_clean.pivot_table(
    index=['country', 'year'],
    columns='granularity',
    values=['basic_pct', 'safely_managed_pct']
)
display(df_water_pivot)

#Aplatir les colonnes multi-niveaux
df_water_pivot.columns = [f"{val}_{gran.lower()}" for val, gran in df_water_pivot.columns]
df_water_pivot = df_water_pivot.reset_index()
display(df_water_pivot)

df_water_pivot['no_acces_pct']       = (100 -df_water_pivot['basic_pct_total']).round(2)
df_water_pivot['no_acces_rural_pct'] = (100 - df_water_pivot['basic_pct_rural']).round(2)
df_water_pivot['no_acces_urban_pct'] = (100 - df_water_pivot['basic_pct_urban']).round(2)

print("✅ Colonnes no_acces ajoutées")
print(f"   {df_water_pivot.shape[0]} lignes × {df_water_pivot.shape[1]} colonnes")
print(df_water_pivot[['country', 'year', 'no_acces_pct', 'no_acces_rural_pct', 'no_acces_urban_pct']].head(3))
display(df_water_pivot)

#On ajoute une colonne 'country_year' qui non permettra de faire les liaisons dans Power BI
df_water_pivot['country_year'] = df_water_pivot['country'] + '_' + df_water_pivot['year'].astype(str)

# --- Vérifier df ---
print("\n🎯 --- ÉTAT FINAL APRÈS NETTOYAGE & PIVOT ---")
inspector(df_water_pivot)

# --- Export fichier ---
df_water_pivot.to_csv("df_water_clean.csv", index=False, sep=';', decimal=',', encoding='utf-8-sig')

print("✅ Fichier exporté")

📊 --- ÉTAT INITIAL ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 10476 ; Nb de colonnes: 5

----------------------
Types de données:
Year                                                             int64
Country                                                         object
Granularity                                                     object
Population using at least basic drinking-water services (%)    float64
Population using safely managed drinking-water services (%)    float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Year                                                             18
Country                                                         194
Granularity                                                       3
Population using at least basic drinking-water services (%)    7704
Population using safely managed drinking-water services (%)    2877
dtype: int64

----------------------
Valeurs manquantes:
Year                                                              0
Country                                                           0
Granularity                                                       0
Population using at least basic drinking-water services (%)    1061
Population using safely managed drinking-water services (%)    7190
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Year,Country,Granularity,Population using at least basic drinking-water services (%),Population using safely managed drinking-water services (%)
0,2000,Afghanistan,Rural,21.61913,NaN
1,2000,Afghanistan,Total,27.77190,NaN
2,2000,Afghanistan,Urban,49.48745,NaN
3,2000,Albania,Rural,81.78472,NaN
4,2000,Albania,Total,87.86662,49.29324
...,...,...,...,...,...
10471,2017,Zambia,Total,59.96376,NaN
10472,2017,Zambia,Urban,83.86312,46.24515
10473,2017,Zimbabwe,Rural,49.80476,NaN
10474,2017,Zimbabwe,Total,64.05123,NaN
10475,2017,Zimbabwe,Urban,93.99767,NaN

##############################################################################

       year      country granularity  basic_pct  safely_managed_pct
0      2000  Afghanistan       Rural   21.61913                 NaN
1      2000  Afghanistan       Total   27.77190                 NaN
2      2000  Afghanistan       Urban   49.48745                 NaN
3      2000      Albania       Rural   81.78472                 NaN
4      2000      Albania       Total   87.86662            49.29324
...     ...          ...         ...        ...                 ...
10471  2017       Zambia       Total   59.96376                 NaN
10472  2017       Zambia       Urban   83.86312            46.24515
10473  2017     Zimbabwe       Rural   49.80476                 NaN
10474  2017     Zimbabwe       Total   64.05123                 NaN
10475  2017     Zimbabwe       Urban   93.99767                 NaN

[10476 rows x 5 columns]

                 basic_pct                     safely_managed_pct
granularity          Rural     Total     Urban              Rural Total Urban
country     year
Afghanistan 2000  21.61913  27.77190  49.48745                NaN   NaN   NaN
            2001  21.61913  27.79726  49.48745                NaN   NaN   NaN
            2002  23.59988  29.90076  51.90447                NaN   NaN   NaN
            2003  25.58063  32.00507  54.32149                NaN   NaN   NaN
            2004  27.56138  34.12623  56.73851                NaN   NaN   NaN
...                    ...       ...       ...                ...   ...   ...
Zimbabwe    2013  52.26732  65.97417  94.24335                NaN   NaN   NaN
            2014  51.64819  65.47338  94.18200                NaN   NaN   NaN
            2015  51.03139  64.98583  94.12061                NaN   NaN   NaN
            2016  50.41692  64.51162  94.05916                NaN   NaN   NaN
            2017  49.80476  64.05123  93.99767                NaN   NaN   NaN

[3455 rows x 6 columns]

,country,year,basic_pct_rural,basic_pct_total,basic_pct_urban,safely_managed_pct_rural,safely_managed_pct_total,safely_managed_pct_urban
0,Afghanistan,2000,21.61913,27.77190,49.48745,NaN,NaN,NaN
1,Afghanistan,2001,21.61913,27.79726,49.48745,NaN,NaN,NaN
2,Afghanistan,2002,23.59988,29.90076,51.90447,NaN,NaN,NaN
3,Afghanistan,2003,25.58063,32.00507,54.32149,NaN,NaN,NaN
4,Afghanistan,2004,27.56138,34.12623,56.73851,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
3450,Zimbabwe,2013,52.26732,65.97417,94.24335,NaN,NaN,NaN
3451,Zimbabwe,2014,51.64819,65.47338,94.18200,NaN,NaN,NaN
3452,Zimbabwe,2015,51.03139,64.98583,94.12061,NaN,NaN,NaN
3453,Zimbabwe,2016,50.41692,64.51162,94.05916,NaN,NaN,NaN
3454,Zimbabwe,2017,49.80476,64.05123,93.99767,NaN,NaN,NaN

✅ Colonnes no_acces ajoutées
   3455 lignes × 11 colonnes
       country  year  no_acces_pct  no_acces_rural_pct  no_acces_urban_pct
0  Afghanistan  2000         72.23               78.38               50.51
1  Afghanistan  2001         72.20               78.38               50.51
2  Afghanistan  2002         70.10               76.40               48.10

,country,year,basic_pct_rural,basic_pct_total,basic_pct_urban,safely_managed_pct_rural,safely_managed_pct_total,safely_managed_pct_urban,no_acces_pct,no_acces_rural_pct,no_acces_urban_pct
0,Afghanistan,2000,21.61913,27.77190,49.48745,NaN,NaN,NaN,72.23,78.38,50.51
1,Afghanistan,2001,21.61913,27.79726,49.48745,NaN,NaN,NaN,72.20,78.38,50.51
2,Afghanistan,2002,23.59988,29.90076,51.90447,NaN,NaN,NaN,70.10,76.40,48.10
3,Afghanistan,2003,25.58063,32.00507,54.32149,NaN,NaN,NaN,67.99,74.42,45.68
4,Afghanistan,2004,27.56138,34.12623,56.73851,NaN,NaN,NaN,65.87,72.44,43.26
...,...,...,...,...,...,...,...,...,...,...,...
3450,Zimbabwe,2013,52.26732,65.97417,94.24335,NaN,NaN,NaN,34.03,47.73,5.76
3451,Zimbabwe,2014,51.64819,65.47338,94.18200,NaN,NaN,NaN,34.53,48.35,5.82
3452,Zimbabwe,2015,51.03139,64.98583,94.12061,NaN,NaN,NaN,35.01,48.97,5.88
3453,Zimbabwe,2016,50.41692,64.51162,94.05916,NaN,NaN,NaN,35.49,49.58,5.94
3454,Zimbabwe,2017,49.80476,64.05123,93.99767,NaN,NaN,NaN,35.95,50.20,6.00

🎯 --- ÉTAT FINAL APRÈS NETTOYAGE & PIVOT ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 3455 ; Nb de colonnes: 12

----------------------
Types de données:
country                      object
year                          int64
basic_pct_rural             float64
basic_pct_total             float64
basic_pct_urban             float64
safely_managed_pct_rural    float64
safely_managed_pct_total    float64
safely_managed_pct_urban    float64
no_acces_pct                float64
no_acces_rural_pct          float64
no_acces_urban_pct          float64
country_year                 object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
country                      194
year                          18
basic_pct_rural             2404
basic_pct_total             2958
basic_pct_urban             2368
safely_managed_pct_rural     569
safely_managed_pct_total    1508
safely_managed_pct_urban     802
no_acces_pct                1963
no_acces_rural_pct          1997
no_acces_urban_pct          1359
country_year                3455
dtype: int64

----------------------
Valeurs manquantes:
country                        0
year                           0
basic_pct_rural              502
basic_pct_total                6
basic_pct_urban              442
safely_managed_pct_rural    2843
safely_managed_pct_total    1710
safely_managed_pct_urban    2526
no_acces_pct                   6
no_acces_rural_pct           502
no_acces_urban_pct           442
country_year                   0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,country,year,basic_pct_rural,basic_pct_total,basic_pct_urban,safely_managed_pct_rural,safely_managed_pct_total,safely_managed_pct_urban,no_acces_pct,no_acces_rural_pct,no_acces_urban_pct,country_year
0,Afghanistan,2000,21.61913,27.77190,49.48745,NaN,NaN,NaN,72.23,78.38,50.51,Afghanistan_2000
1,Afghanistan,2001,21.61913,27.79726,49.48745,NaN,NaN,NaN,72.20,78.38,50.51,Afghanistan_2001
2,Afghanistan,2002,23.59988,29.90076,51.90447,NaN,NaN,NaN,70.10,76.40,48.10,Afghanistan_2002
3,Afghanistan,2003,25.58063,32.00507,54.32149,NaN,NaN,NaN,67.99,74.42,45.68,Afghanistan_2003
4,Afghanistan,2004,27.56138,34.12623,56.73851,NaN,NaN,NaN,65.87,72.44,43.26,Afghanistan_2004
...,...,...,...,...,...,...,...,...,...,...,...,...
3450,Zimbabwe,2013,52.26732,65.97417,94.24335,NaN,NaN,NaN,34.03,47.73,5.76,Zimbabwe_2013
3451,Zimbabwe,2014,51.64819,65.47338,94.18200,NaN,NaN,NaN,34.53,48.35,5.82,Zimbabwe_2014
3452,Zimbabwe,2015,51.03139,64.98583,94.12061,NaN,NaN,NaN,35.01,48.97,5.88,Zimbabwe_2015
3453,Zimbabwe,2016,50.41692,64.51162,94.05916,NaN,NaN,NaN,35.49,49.58,5.94,Zimbabwe_2016
3454,Zimbabwe,2017,49.80476,64.05123,93.99767,NaN,NaN,NaN,35.95,50.20,6.00,Zimbabwe_2017

##############################################################################
✅ Fichier exporté

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Nettoyage du fichier 'MortalityRateAttributedToWater.csv'</h3>
</div>

In [6]:
# --- Nettoyage ---
df_mortality_clean = df_mortality.copy()
print("📊 --- ÉTAT INITIAL ---")
inspector(df_mortality_clean)

df_mortality_clean = df_mortality_clean.rename(columns={
    'Year': 'year',
    'Country': 'country',
    'Granularity': 'granularity',
    'Mortality rate attributed to exposure to unsafe WASH services': 'wash_mortality_rate',
    'WASH deaths': 'wash_deaths'
})

#Enlève les éléments entre parenthèse dans la colonne 'country' pour que PowerBI reconnaisse les pays
df_mortality_clean['country'] = df_mortality_clean['country'].str.replace(r'\s*\(.*\)', '', regex=True)

df_mortality_clean['country'] = df_mortality_clean['country'].replace('Congo', 'Republic of Congo')

#Création d'une colonne par granularité
df_mortality_pivot = df_mortality_clean.pivot_table(
    index=['country', 'year'],
    columns='granularity',
    values=['wash_mortality_rate', 'wash_deaths'])

df_mortality_pivot.columns = [
    f"{col[0].lower()}_{col[1].lower()}" 
    for col in df_mortality_pivot.columns
]

df_mortality_pivot = df_mortality_pivot.reset_index()

#On ajoute une colonne 'country_year' qui non permettra de faire les liaisons dans Power BI
df_mortality_pivot['country_year'] = df_mortality_pivot['country'] + '_' + df_mortality_pivot['year'].astype(str)

# --- Vérifier df ---
print("\n🎯 --- ÉTAT FINAL APRÈS NETTOYAGE ---")
inspector(df_mortality_pivot)

# --- Export fichier ---
df_mortality_pivot.to_csv("df_mortality_clean.csv", index=False, sep=';', decimal=',', encoding='utf-8-sig')

print("✅ Fichier exporté")

📊 --- ÉTAT INITIAL ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 549 ; Nb de colonnes: 5

----------------------
Types de données:
Year                                                               int64
Country                                                           object
Granularity                                                       object
Mortality rate attributed to exposure to unsafe WASH services    float64
WASH deaths                                                      float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Year                                                               1
Country                                                          183
Granularity                                                        3
Mortality rate attributed to exposure to unsafe WASH services    548
WASH deaths                                                      183
dtype: int64

----------------------
Valeurs manquantes:
Year                                                               0
Country                                                            0
Granularity                                                        0
Mortality rate attributed to exposure to unsafe WASH services      0
WASH deaths                                                      366
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Year,Country,Granularity,Mortality rate attributed to exposure to unsafe WASH services,WASH deaths
0,2016,Afghanistan,Female,15.31193,NaN
1,2016,Afghanistan,Male,12.61297,NaN
2,2016,Afghanistan,Total,13.92067,4824.353
3,2016,Albania,Female,0.12552,NaN
4,2016,Albania,Male,0.20650,NaN
...,...,...,...,...,...
544,2016,Zambia,Male,36.61913,NaN
545,2016,Zambia,Total,34.91273,5792.504
546,2016,Zimbabwe,Female,22.16388,NaN
547,2016,Zimbabwe,Male,27.06688,NaN
548,2016,Zimbabwe,Total,24.55074,3965.033

##############################################################################

🎯 --- ÉTAT FINAL APRÈS NETTOYAGE ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 183 ; Nb de colonnes: 7

----------------------
Types de données:
country                        object
year                            int64
wash_deaths_total             float64
wash_mortality_rate_female    float64
wash_mortality_rate_male      float64
wash_mortality_rate_total     float64
country_year                   object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
country                       183
year                            1
wash_deaths_total             183
wash_mortality_rate_female    183
wash_mortality_rate_male      183
wash_mortality_rate_total     183
country_year                  183
dtype: int64

----------------------
Valeurs manquantes:
country                       0
year                          0
wash_deaths_total             0
wash_mortality_rate_female    0
wash_mortality_rate_male      0
wash_mortality_rate_total     0
country_year                  0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,country,year,wash_deaths_total,wash_mortality_rate_female,wash_mortality_rate_male,wash_mortality_rate_total,country_year
0,Afghanistan,2016,4824.35300,15.31193,12.61297,13.92067,Afghanistan_2016
1,Albania,2016,4.86975,0.12552,0.20650,0.16641,Albania_2016
2,Algeria,2016,758.21000,2.19890,1.72837,1.86723,Algeria_2016
3,Angola,2016,14065.20000,45.15024,52.62506,48.81467,Angola_2016
4,Antigua and Barbuda,2016,0.11513,0.10419,0.12469,0.11403,Antigua and Barbuda_2016
...,...,...,...,...,...,...,...
178,Venezuela,2016,438.89230,1.36928,1.41152,1.39030,Venezuela_2016
179,Viet Nam,2016,1532.77700,1.13807,2.11376,1.62080,Viet Nam_2016
180,Yemen,2016,2814.49500,11.77016,8.66892,10.20328,Yemen_2016
181,Zambia,2016,5792.50400,33.23213,36.61913,34.91273,Zambia_2016
182,Zimbabwe,2016,3965.03300,22.16388,27.06688,24.55074,Zimbabwe_2016

##############################################################################
✅ Fichier exporté

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Nettoyage du fichier 'PoliticalStability.csv'</h3>
</div>

In [7]:
# --- Nettoyage ---
df_stability_clean = df_stability.copy()
print("📊 --- ÉTAT INITIAL ---")
inspector(df_stability_clean)

#On garde uniquement 'Total'
df_stability_clean = df_stability_clean[df_stability_clean['Granularity'] == 'Total']

#On supprime la colonne 'Granularity' devenue inutile car il ne reste que 'Total'
df_stability_clean = df_stability_clean.drop(columns=['Granularity'])

#Renommage
df_stability_clean.columns = ['country', 'year', 'political_stability']


#Enlève les éléments entre parenthèse dans la colonne 'country' pour que PowerBI reconnaisse les pays
df_stability_clean['country'] = df_stability_clean['country'].str.replace(r'\s*\(.*\)', '', regex=True)
df_stability_clean['country'] = df_stability_clean['country'].replace('North Macedonia', 'Republic of North Macedonia')
df_stability_clean['country'] = df_stability_clean['country'].replace('Congo', 'Republic of Congo')

#On ajoute une colonne 'country_year' qui non permettra de faire les liaisons dans Power BI
df_stability_clean['country_year'] = df_stability_clean['country'] + '_' + df_stability_clean['year'].astype(str)


#Ajout de la colonne 'wash_mortality_rate_total'
df_stability_clean = pd.merge(
    df_stability_clean, df_mortality_pivot[['country_year', 'wash_mortality_rate_total']], on='country_year', how="left" ########### df_mortality_pivot
)
display(df_stability_clean)

# Ajout de la colonne 'basic_pct_total'
df_stability_clean = pd.merge(
    df_stability_clean, df_water_pivot[['country_year', 'basic_pct_total']], on='country_year', how="left"
)
display(df_stability_clean)

mask_2016 = df_stability_clean['year'] == 2016
val_min = df_stability_clean.loc[mask_2016, 'wash_mortality_rate_total'].min()
val_max = df_stability_clean.loc[mask_2016, 'wash_mortality_rate_total'].max()

mortality_norm = 1 - (df_stability_clean.loc[mask_2016, 'wash_mortality_rate_total'] - val_min) / (val_max - val_min)

df_stability_clean.loc[mask_2016, 'gov_score'] = (
    (mortality_norm + df_stability_clean.loc[mask_2016, 'basic_pct_total'] / 100) / 2
).round(4)

# --- Vérifier df ---
print("\n🎯 --- ÉTAT FINAL APRÈS NETTOYAGE ---")
inspector(df_stability_clean)

# --- Export fichier ---
df_stability_clean.to_csv("df_stability_clean.csv", index=False, sep=';', decimal=',', encoding='utf-8-sig')

print("✅ Fichier exporté")

📊 --- ÉTAT INITIAL ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 3526 ; Nb de colonnes: 4

----------------------
Types de données:
Country                 object
Year                     int64
Political_Stability    float64
Granularity             object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Country                200
Year                    18
Political_Stability    444
Granularity              1
dtype: int64

----------------------
Valeurs manquantes:
Country                0
Year                   0
Political_Stability    0
Granularity            0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

          Country  Year  Political_Stability Granularity
0     Afghanistan  2000                -2.44       Total
1     Afghanistan  2002                -2.04       Total
2     Afghanistan  2003                -2.20       Total
3     Afghanistan  2004                -2.30       Total
4     Afghanistan  2005                -2.07       Total
...           ...   ...                  ...         ...
3521     Zimbabwe  2014                -0.71       Total
3522     Zimbabwe  2015                -0.62       Total
3523     Zimbabwe  2016                -0.62       Total
3524     Zimbabwe  2017                -0.71       Total
3525     Zimbabwe  2018                -0.71       Total

[3526 rows x 4 columns]

##############################################################################

,country,year,political_stability,country_year,wash_mortality_rate_total
0,Afghanistan,2000,-2.44,Afghanistan_2000,NaN
1,Afghanistan,2002,-2.04,Afghanistan_2002,NaN
2,Afghanistan,2003,-2.20,Afghanistan_2003,NaN
3,Afghanistan,2004,-2.30,Afghanistan_2004,NaN
4,Afghanistan,2005,-2.07,Afghanistan_2005,NaN
...,...,...,...,...,...
3521,Zimbabwe,2014,-0.71,Zimbabwe_2014,NaN
3522,Zimbabwe,2015,-0.62,Zimbabwe_2015,NaN
3523,Zimbabwe,2016,-0.62,Zimbabwe_2016,24.55074
3524,Zimbabwe,2017,-0.71,Zimbabwe_2017,NaN
3525,Zimbabwe,2018,-0.71,Zimbabwe_2018,NaN

,country,year,political_stability,country_year,wash_mortality_rate_total,basic_pct_total
0,Afghanistan,2000,-2.44,Afghanistan_2000,NaN,27.77190
1,Afghanistan,2002,-2.04,Afghanistan_2002,NaN,29.90076
2,Afghanistan,2003,-2.20,Afghanistan_2003,NaN,32.00507
3,Afghanistan,2004,-2.30,Afghanistan_2004,NaN,34.12623
4,Afghanistan,2005,-2.07,Afghanistan_2005,NaN,36.26526
...,...,...,...,...,...,...
3521,Zimbabwe,2014,-0.71,Zimbabwe_2014,NaN,65.47338
3522,Zimbabwe,2015,-0.62,Zimbabwe_2015,NaN,64.98583
3523,Zimbabwe,2016,-0.62,Zimbabwe_2016,24.55074,64.51162
3524,Zimbabwe,2017,-0.71,Zimbabwe_2017,NaN,64.05123
3525,Zimbabwe,2018,-0.71,Zimbabwe_2018,NaN,NaN

🎯 --- ÉTAT FINAL APRÈS NETTOYAGE ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 3526 ; Nb de colonnes: 7

----------------------
Types de données:
country                       object
year                           int64
political_stability          float64
country_year                  object
wash_mortality_rate_total    float64
basic_pct_total              float64
gov_score                    float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
country                       200
year                           18
political_stability           444
country_year                 3526
wash_mortality_rate_total     182
basic_pct_total              2750
gov_score                     158
dtype: int64

----------------------
Valeurs manquantes:
country                         0
year                            0
political_stability             0
country_year                    0
wash_mortality_rate_total    3344
basic_pct_total               360
gov_score                    3344
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,country,year,political_stability,country_year,wash_mortality_rate_total,basic_pct_total,gov_score
0,Afghanistan,2000,-2.44,Afghanistan_2000,NaN,27.77190,NaN
1,Afghanistan,2002,-2.04,Afghanistan_2002,NaN,29.90076,NaN
2,Afghanistan,2003,-2.20,Afghanistan_2003,NaN,32.00507,NaN
3,Afghanistan,2004,-2.30,Afghanistan_2004,NaN,34.12623,NaN
4,Afghanistan,2005,-2.07,Afghanistan_2005,NaN,36.26526,NaN
...,...,...,...,...,...,...,...
3521,Zimbabwe,2014,-0.71,Zimbabwe_2014,NaN,65.47338,NaN
3522,Zimbabwe,2015,-0.62,Zimbabwe_2015,NaN,64.98583,NaN
3523,Zimbabwe,2016,-0.62,Zimbabwe_2016,24.55074,64.51162,0.7011
3524,Zimbabwe,2017,-0.71,Zimbabwe_2017,NaN,64.05123,NaN
3525,Zimbabwe,2018,-0.71,Zimbabwe_2018,NaN,NaN,NaN

##############################################################################
✅ Fichier exporté

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Nettoyage du fichier 'RegionCountry.csv'</h3>
</div>

In [8]:
# --- Nettoyage ---
df_geo_clean = df_geo.copy()
print("📊 --- ÉTAT INITIAL ---")
inspector(df_geo_clean)

#Renommage
df_geo_clean.columns = ['region', 'country']

#Enlève les éléments entre parenthèse dans la colonne 'country' pour que PowerBI reconnaisse les pays
df_geo_clean['country'] = df_geo_clean['country'].str.replace(r'\s*\(.*\)', '', regex=True)

#Renomme 'Congo' pour qu'il soit identifier par PowerBI
df_geo_clean['country'] = df_geo_clean['country'].replace('Congo', 'Republic of Congo')

# --- Vérifier df ---
print("\n🎯 --- ÉTAT FINAL APRÈS NETTOYAGE ---")
inspector(df_geo_clean)

# --- Export fichier ---
df_geo_clean.to_csv("df_geo_clean.csv", index=False, encoding='utf-8-sig')

print("✅ Fichier exporté")

📊 --- ÉTAT INITIAL ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 194 ; Nb de colonnes: 2

----------------------
Types de données:
REGION (DISPLAY)     object
COUNTRY (DISPLAY)    object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
REGION (DISPLAY)       6
COUNTRY (DISPLAY)    194
dtype: int64

----------------------
Valeurs manquantes:
REGION (DISPLAY)     0
COUNTRY (DISPLAY)    0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

          REGION (DISPLAY)                   COUNTRY (DISPLAY)
0                   Europe                             Albania
1                   Europe                             Andorra
2                   Europe                             Armenia
3          Western Pacific                           Australia
4                   Europe                             Austria
..                     ...                                 ...
189  Eastern Mediterranean                United Arab Emirates
190               Americas  Venezuela (Bolivarian Republic of)
191        Western Pacific                            Viet Nam
192  Eastern Mediterranean                               Yemen
193                 Africa                            Zimbabwe

[194 rows x 2 columns]

##############################################################################

🎯 --- ÉTAT FINAL APRÈS NETTOYAGE ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 194 ; Nb de colonnes: 2

----------------------
Types de données:
region     object
country    object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
region       6
country    194
dtype: int64

----------------------
Valeurs manquantes:
region     0
country    0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

                    region               country
0                   Europe               Albania
1                   Europe               Andorra
2                   Europe               Armenia
3          Western Pacific             Australia
4                   Europe               Austria
..                     ...                   ...
189  Eastern Mediterranean  United Arab Emirates
190               Americas             Venezuela
191        Western Pacific              Viet Nam
192  Eastern Mediterranean                 Yemen
193                 Africa              Zimbabwe

[194 rows x 2 columns]

##############################################################################
✅ Fichier exporté

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Nettoyage du fichier 'Population.csv'</h3>
</div>

In [9]:
# --- Nettoyage ---
df_pop_clean = df_pop.copy()
print("📊 --- ÉTAT INITIAL ---")
inspector(df_pop_clean)

#Renommage des colonnes
df_pop_clean.columns = ['country', 'granularity', 'year', 'population']

#Enlève les éléments entre parenthèse dans la colonne 'country' pour que PowerBI reconnaisse les pays
df_pop_clean['country'] = df_pop_clean['country'].str.replace(r'\s*\(.*\)', '', regex=True)

df_pop_clean['country'] = df_pop_clean['country'].replace('Congo', 'Republic of Congo')

#On multiplie la colone 'population' par 1000 pour avoir la notation française et ne pas avoir de point qui vont par la suite se transformer en virgule
df_pop_clean['population'] = df_pop_clean['population']*1000

#On garde uniquement Total / Urban / Rural / Male / Female
df_pop_clean = df_pop_clean[df_pop_clean['granularity'].isin(['Total', 'Urban', 'Rural', 'Male', 'Female'])]
display(df_pop_clean)

#Extraction des listes de pays uniques (en convertissant en "set" pour les opérations mathématiques)
countries_pop = set(df_pop_clean['country'].unique())
countries_water = set(df_water_pivot['country'].unique())

#Pays présents dans 'df_pop_clean' mais pas dans 'df_water_pivot'
only_in_pop = countries_pop - countries_water

#Pays présents dans 'df_water_pivot' mais pas dans 'df_pop_clean'
only_in_water = countries_water - countries_pop

# --- Affichage des résultats ---

print(f"Nombre de pays dans 'df_pop_clean' : {len(countries_pop)}")
print(f"Nombre de pays dans 'df_water_pivot' : {len(countries_water)}")
print("-" * 40)

print(f"\n🔴 Pays dans 'df_pop_clean' qui n'ont PAS de correspondance dans 'df_water_pivot' ({len(only_in_pop)}) :")
print(sorted(list(only_in_pop)))

print(f"\n🔵 Pays dans 'df_water_pivot' qui n'ont PAS de correspondance dans 'df_pop_clean' ({len(only_in_water)}) :")
print(sorted(list(only_in_water)))

df_pop_clean['country'] = df_pop_clean['country'].replace('North Macedonia', 'Republic of North Macedonia')


print("-----------------------------------------------------")
#Pour éviter que Power BI rate des jointures, on regarde si des pays de nos faits sont absents de la table df_geo_clean
all_countries_in_facts = set(
    pd.concat(
        [
            df_pop_clean["country"],
            df_water_clean["country"],
            df_mortality_clean["country"],
            df_stability_clean["country"],
        ]
    ).unique()
)
geo_countries = set(df_geo_clean["country"].unique())
missing_geo = all_countries_in_facts - geo_countries

if missing_geo:
    print(f"⚠️ Attention : {len(missing_geo)} pays présents dans les données n'ont pas de correspondance géographique.\n")
    print("Voici la liste des pays concernés :")
    
#On trie la liste par ordre alphabétique pour que ce soit plus lisible
    for country in sorted(missing_geo):
        print(f" - {country}")
else:
    print("✅ Parfait ! Tous les pays ont une correspondance dans la table géographique.")
print("-----------------------------------------------------")

df_pop_clean = df_pop_clean[df_pop_clean['country'].isin(geo_countries)]
display(df_pop_clean)

#Pivot : une ligne par pays/année
df_pop_pivot = df_pop_clean.pivot_table(
    index=['country', 'year'],
    columns='granularity',
    values='population'
).reset_index()
display(df_pop_pivot)

df_pop_pivot.columns = [
    f"pop_{col.lower()}" if col not in ['country', 'year'] else col 
    for col in df_pop_pivot.columns
]
display(df_pop_pivot)

#Fusion avec la table région
df_pop_pivot = df_pop_pivot.merge(df_geo_clean, on='country', how='left') 

#Calcul des pourcentages avec .div() pour éviter les erreurs si pop_total est nul ou NaN
df_pop_pivot['urban_pct'] = (df_pop_pivot['pop_urban'].div(df_pop_pivot['pop_total']) * 100).round(2).clip(upper=100)
df_pop_pivot['rural_pct'] = (df_pop_pivot['pop_rural'].div(df_pop_pivot['pop_total']) * 100).round(2).clip(upper=100)

#On ajoute une colonne 'country_year' qui non permettra de faire les liaisons dans Power BI
df_pop_pivot['country_year'] = df_pop_pivot['country'] + '_' + df_pop_pivot['year'].astype(str)

# --- Vérifier df ---
print("\n🎯 --- ÉTAT FINAL APRÈS NETTOYAGE ---")
inspector(df_pop_pivot)

# --- Export fichier ---
df_pop_pivot.to_csv("df_pop_clean.csv", index=False, sep=';', decimal=',', encoding='utf-8-sig')

print("✅ Fichier exporté")

📊 --- ÉTAT INITIAL ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 20914 ; Nb de colonnes: 4

----------------------
Types de données:
Country         object
Granularity     object
Year             int64
Population     float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Country          239
Granularity        5
Year              19
Population     20515
dtype: int64

----------------------
Valeurs manquantes:
Country        0
Granularity    0
Year           0
Population     0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

           Country Granularity  Year  Population
0      Afghanistan       Total  2000   20779.953
1      Afghanistan        Male  2000   10689.508
2      Afghanistan      Female  2000   10090.449
3      Afghanistan       Rural  2000   15657.474
4      Afghanistan       Urban  2000    4436.282
...            ...         ...   ...         ...
20909     Zimbabwe       Total  2018   14438.802
20910     Zimbabwe        Male  2018    6879.119
20911     Zimbabwe      Female  2018    7559.693
20912     Zimbabwe       Rural  2018   11465.748
20913     Zimbabwe       Urban  2018    5447.513

[20914 rows x 4 columns]

##############################################################################

           country granularity  year  population
0      Afghanistan       Total  2000  20779953.0
1      Afghanistan        Male  2000  10689508.0
2      Afghanistan      Female  2000  10090449.0
3      Afghanistan       Rural  2000  15657474.0
4      Afghanistan       Urban  2000   4436282.0
...            ...         ...   ...         ...
20909     Zimbabwe       Total  2018  14438802.0
20910     Zimbabwe        Male  2018   6879119.0
20911     Zimbabwe      Female  2018   7559693.0
20912     Zimbabwe       Rural  2018  11465748.0
20913     Zimbabwe       Urban  2018   5447513.0

[20914 rows x 4 columns]

Nombre de pays dans 'df_pop_clean' : 238
Nombre de pays dans 'df_water_pivot' : 194
----------------------------------------

🔴 Pays dans 'df_pop_clean' qui n'ont PAS de correspondance dans 'df_water_pivot' (45) :
['American Samoa', 'Anguilla', 'Aruba', 'Bermuda', 'Bonaire, Sint Eustatius and Saba', 'British Virgin Islands', 'Cayman Islands', 'Channel Islands', 'China, Hong Kong SAR', 'China, Macao SAR', 'China, Taiwan Province of', 'China, mainland', 'Curaçao', 'Falkland Islands', 'Faroe Islands', 'French Guyana', 'French Polynesia', 'Gibraltar', 'Greenland', 'Guadeloupe', 'Guam', 'Holy See', 'Isle of Man', 'Liechtenstein', 'Martinique', 'Mayotte', 'Montserrat', 'Netherlands Antilles', 'New Caledonia', 'North Macedonia', 'Northern Mariana Islands', 'Palestine', 'Puerto Rico', 'Réunion', 'Saint Barthélemy', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Pierre and Miquelon', 'Saint-Martin', 'Serbia and Montenegro', 'Sint Maarten', 'Tokelau', 'Turks and Caicos Islands', 'United States Virgin Islands', 'Wallis and Futuna Islands', 'Western Sahara']

🔵 Pays dans 'df_water_pivot' qui n'ont PAS de correspondance dans 'df_pop_clean' (1) :
['Republic of North Macedonia']
-----------------------------------------------------
⚠️ Attention : 44 pays présents dans les données n'ont pas de correspondance géographique.

Voici la liste des pays concernés :
 - American Samoa
 - Anguilla
 - Aruba
 - Bermuda
 - Bonaire, Sint Eustatius and Saba
 - British Virgin Islands
 - Cayman Islands
 - Channel Islands
 - China, Hong Kong SAR
 - China, Macao SAR
 - China, Taiwan Province of
 - China, mainland
 - Curaçao
 - Falkland Islands
 - Faroe Islands
 - French Guyana
 - French Polynesia
 - Gibraltar
 - Greenland
 - Guadeloupe
 - Guam
 - Holy See
 - Isle of Man
 - Liechtenstein
 - Martinique
 - Mayotte
 - Montserrat
 - Netherlands Antilles
 - New Caledonia
 - Northern Mariana Islands
 - Palestine
 - Puerto Rico
 - Réunion
 - Saint Barthélemy
 - Saint Helena, Ascension and Tristan da Cunha
 - Saint Pierre and Miquelon
 - Saint-Martin
 - Serbia and Montenegro
 - Sint Maarten
 - Tokelau
 - Turks and Caicos Islands
 - United States Virgin Islands
 - Wallis and Futuna Islands
 - Western Sahara
-----------------------------------------------------

           country granularity  year  population
0      Afghanistan       Total  2000  20779953.0
1      Afghanistan        Male  2000  10689508.0
2      Afghanistan      Female  2000  10090449.0
3      Afghanistan       Rural  2000  15657474.0
4      Afghanistan       Urban  2000   4436282.0
...            ...         ...   ...         ...
20909     Zimbabwe       Total  2018  14438802.0
20910     Zimbabwe        Male  2018   6879119.0
20911     Zimbabwe      Female  2018   7559693.0
20912     Zimbabwe       Rural  2018  11465748.0
20913     Zimbabwe       Urban  2018   5447513.0

[17892 rows x 4 columns]

granularity,country,year,Female,Male,Rural,Total,Urban
0,Afghanistan,2000,10090449.0,10689508.0,15657474.0,20779953.0,4436282.0
1,Afghanistan,2001,10489238.0,11117754.0,16318324.0,21606988.0,4648139.0
2,Afghanistan,2002,10958668.0,11642106.0,17086910.0,22600770.0,4893013.0
3,Afghanistan,2003,11466237.0,12214634.0,17909063.0,23680871.0,5155788.0
4,Afghanistan,2004,11962963.0,12763726.0,18692107.0,24726684.0,5426872.0
...,...,...,...,...,...,...,...
3657,Zimbabwe,2014,7126795.0,6459915.0,10402274.0,13586707.0,5009401.0
3658,Zimbabwe,2015,7245864.0,6568778.0,10667966.0,13814629.0,5109485.0
3659,Zimbabwe,2016,7356132.0,6674206.0,10934468.0,14030331.0,5215894.0
3660,Zimbabwe,2017,7459545.0,6777054.0,11201138.0,14236595.0,5328766.0
3661,Zimbabwe,2018,7559693.0,6879119.0,11465748.0,14438802.0,5447513.0

,country,year,pop_female,pop_male,pop_rural,pop_total,pop_urban
0,Afghanistan,2000,10090449.0,10689508.0,15657474.0,20779953.0,4436282.0
1,Afghanistan,2001,10489238.0,11117754.0,16318324.0,21606988.0,4648139.0
2,Afghanistan,2002,10958668.0,11642106.0,17086910.0,22600770.0,4893013.0
3,Afghanistan,2003,11466237.0,12214634.0,17909063.0,23680871.0,5155788.0
4,Afghanistan,2004,11962963.0,12763726.0,18692107.0,24726684.0,5426872.0
...,...,...,...,...,...,...,...
3657,Zimbabwe,2014,7126795.0,6459915.0,10402274.0,13586707.0,5009401.0
3658,Zimbabwe,2015,7245864.0,6568778.0,10667966.0,13814629.0,5109485.0
3659,Zimbabwe,2016,7356132.0,6674206.0,10934468.0,14030331.0,5215894.0
3660,Zimbabwe,2017,7459545.0,6777054.0,11201138.0,14236595.0,5328766.0
3661,Zimbabwe,2018,7559693.0,6879119.0,11465748.0,14438802.0,5447513.0

🎯 --- ÉTAT FINAL APRÈS NETTOYAGE ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 3662 ; Nb de colonnes: 11

----------------------
Types de données:
country          object
year              int64
pop_female      float64
pop_male        float64
pop_rural       float64
pop_total       float64
pop_urban       float64
region           object
urban_pct       float64
rural_pct       float64
country_year     object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
country          194
year              19
pop_female      3453
pop_male        3453
pop_rural       3583
pop_total       3659
pop_urban       3657
region             6
urban_pct       2893
rural_pct       2890
country_year    3662
dtype: int64

----------------------
Valeurs manquantes:
country           0
year              0
pop_female      209
pop_male        209
pop_rural         0
pop_total         0
pop_urban         0
region            0
urban_pct         0
rural_pct         0
country_year      0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,country,year,pop_female,pop_male,pop_rural,pop_total,pop_urban,region,urban_pct,rural_pct,country_year
0,Afghanistan,2000,10090449.0,10689508.0,15657474.0,20779953.0,4436282.0,Eastern Mediterranean,21.35,75.35,Afghanistan_2000
1,Afghanistan,2001,10489238.0,11117754.0,16318324.0,21606988.0,4648139.0,Eastern Mediterranean,21.51,75.52,Afghanistan_2001
2,Afghanistan,2002,10958668.0,11642106.0,17086910.0,22600770.0,4893013.0,Eastern Mediterranean,21.65,75.60,Afghanistan_2002
3,Afghanistan,2003,11466237.0,12214634.0,17909063.0,23680871.0,5155788.0,Eastern Mediterranean,21.77,75.63,Afghanistan_2003
4,Afghanistan,2004,11962963.0,12763726.0,18692107.0,24726684.0,5426872.0,Eastern Mediterranean,21.95,75.59,Afghanistan_2004
...,...,...,...,...,...,...,...,...,...,...,...
3657,Zimbabwe,2014,7126795.0,6459915.0,10402274.0,13586707.0,5009401.0,Africa,36.87,76.56,Zimbabwe_2014
3658,Zimbabwe,2015,7245864.0,6568778.0,10667966.0,13814629.0,5109485.0,Africa,36.99,77.22,Zimbabwe_2015
3659,Zimbabwe,2016,7356132.0,6674206.0,10934468.0,14030331.0,5215894.0,Africa,37.18,77.93,Zimbabwe_2016
3660,Zimbabwe,2017,7459545.0,6777054.0,11201138.0,14236595.0,5328766.0,Africa,37.43,78.68,Zimbabwe_2017
3661,Zimbabwe,2018,7559693.0,6879119.0,11465748.0,14438802.0,5447513.0,Africa,37.73,79.41,Zimbabwe_2018

##############################################################################
✅ Fichier exporté