# <center>**La poule qui chante (entreprise française d’agroalimentaire)**</center>

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 1 - Importation des librairies et chargement des fichiers</h2>
</div>

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">1.1 - Importation des librairies</h3>
</div>

In [1]:
#Importation de la librairie Pandas
import pandas as pd

In [2]:
import pycountry

In [3]:
def get_iso3_exact(country_name):
    try:
        return pycountry.countries.lookup(country_name).alpha_3
    except:
        return None

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">1.2 - Chargement des fichiers</h3>
</div>

In [4]:
#Importation du fichier
df_dispoali_2017 = pd.read_csv("D:/$27.12.2025 Ordinateur/$29.12.2025 Bureau/$GRETA/$P11/données/donnée_Openclassrooms/DisponibiliteAlimentaire_2017.csv")
df_pop = pd.read_csv("D:/$27.12.2025 Ordinateur/$29.12.2025 Bureau/$GRETA/$P11/données/donnée_Openclassrooms/Population_2000_2018.csv")
df_pib_2017 = pd.read_csv("D:/$27.12.2025 Ordinateur/$29.12.2025 Bureau/$GRETA/$P11/données/Data téléchargées/PIB_2017_en_USD.csv")
df_cout_ali_saine_2017 = pd.read_csv("D:/$27.12.2025 Ordinateur/$29.12.2025 Bureau/$GRETA/$P11/données/Data téléchargées/Coût_et_abordabilité_d_une_alimentation_saine_(CoAHD)_2017.csv")
df_stability_2017 = pd.read_csv("D:/$27.12.2025 Ordinateur/$29.12.2025 Bureau/$GRETA/$P11/données/Data téléchargées/Satbilité_politique_par_pays_2017.csv")

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2.1 - Nettoyage - 'DisponibiliteAlimentaire_2017.csv' -> df_dispoali_2017_clean_pivot</h2>
</div>

<div style="border: 1px solid RGB(150, 20, 30); padding: 20px;">
    <h3 style="margin: 0; color: RGB(0, 50, 230); line-height: 1.6;">
        Variables :<br>
        • Production : Ce que le pays produit<br>
        • Importations - Quantité : Ce que le pays achète à l'extérieur<br>
        • Exportations - Quantité : Ce que le pays vend à l'extérieur<br>
        • Disponibilité intérieure : Ce que le pays produit lui-même<br>
        • Disponibilité alimentaire en quantité (kg/personne/an) : Pour mesurer la consommation par habitant
    </h3>
</div>

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Inspection</h3>
</div>

In [5]:
# --- Nettoyage ---
df_dispoali_2017_clean = df_dispoali_2017.copy()
print("📊 --- ÉTAT INITIAL ---")

from mes_fonctions import inspector
inspector(df_dispoali_2017_clean)

📊 --- ÉTAT INITIAL ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 176600 ; Nb de colonnes: 14

----------------------
Types de données:
Code Domaine               object
Domaine                    object
Code zone                   int64
Zone                       object
Code Élément                int64
Élément                    object
Code Produit                int64
Produit                    object
Code année                  int64
Année                       int64
Unité                      object
Valeur                    float64
Symbole                    object
Description du Symbole     object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Code Domaine                 1
Domaine                      1
Code zone                  174
Zone                       174
Code Élément                17
Élément                     17
Code Produit                98
Produit                     98
Code année                   1
Année                        1
Unité                        4
Valeur                    7250
Symbole                      2
Description du Symbole       2
dtype: int64

----------------------
Valeurs manquantes:
Code Domaine              0
Domaine                   0
Code zone                 0
Zone                      0
Code Élément              0
Élément                   0
Code Produit              0
Produit                   0
Code année                0
Année                     0
Unité                     0
Valeur                    0
Symbole                   0
Description du Symbole    0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2511,Blé et produits,2017,2017,Milliers de tonnes,4281.00,S,Données standardisées
1,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,2302.00,S,Données standardisées
2,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2511,Blé et produits,2017,2017,Milliers de tonnes,-119.00,S,Données standardisées
3,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5911,Exportations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,0.00,S,Données standardisées
4,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé et produits,2017,2017,Milliers de tonnes,6701.00,S,Données standardisées
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176595,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,5142,Nourriture,2899,Miscellanees,2017,2017,Milliers de tonnes,19.00,S,Données standardisées
176596,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2899,Miscellanees,2017,2017,kg,1.33,Fc,Donnée calculée
176597,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2017,2017,Kcal/personne/jour,1.00,Fc,Donnée calculée
176598,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2017,2017,g/personne/jour,0.04,Fc,Donnée calculée
176599,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2017,2017,g/personne/jour,0.02,Fc,Donnée calculée

##############################################################################

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Nom des colonnes et suppression</h3>
</div>

In [6]:
nom_colonnes = df_dispoali_2017_clean.columns

for colonne in nom_colonnes:
    print(colonne)

#Modifie directement df_dispoali_2017_clean
#Supprimer colonnes non importante
df_dispoali_2017_clean.drop(
    columns=["Code zone", "Code Domaine", "Domaine", "Code année", "Code Élément", 
             "Code Produit", "Année", "Symbole", "Description du Symbole"], inplace=True
)

display(df_dispoali_2017_clean.head(30))

Code Domaine
Domaine
Code zone
Zone
Code Élément
Élément
Code Produit
Produit
Code année
Année
Unité
Valeur
Symbole
Description du Symbole

,Zone,Élément,Produit,Unité,Valeur
0,Afghanistan,Production,Blé et produits,Milliers de tonnes,4281.00
1,Afghanistan,Importations - Quantité,Blé et produits,Milliers de tonnes,2302.00
2,Afghanistan,Variation de stock,Blé et produits,Milliers de tonnes,-119.00
3,Afghanistan,Exportations - Quantité,Blé et produits,Milliers de tonnes,0.00
4,Afghanistan,Disponibilité intérieure,Blé et produits,Milliers de tonnes,6701.00
5,Afghanistan,Aliments pour animaux,Blé et produits,Milliers de tonnes,76.00
6,Afghanistan,Semences,Blé et produits,Milliers de tonnes,344.00
7,Afghanistan,Pertes,Blé et produits,Milliers de tonnes,642.00
8,Afghanistan,Résidus,Blé et produits,Milliers de tonnes,0.00
9,Afghanistan,Nourriture,Blé et produits,Milliers de tonnes,5640.00
10,Afghanistan,Disponibilité alimentaire en quantité (kg/pers...,Blé et produits,kg,155.39
11,Afghanistan,Disponibilité alimentaire (Kcal/personne/jour),Blé et produits,Kcal/personne/jour,1331.00
12,Afghanistan,Disponibilité de protéines en quantité (g/pers...,Blé et produits,g/personne/jour,35.88
13,Afghanistan,Disponibilité de matière grasse en quantité (g...,Blé et produits,g/personne/jour,4.47
14,Afghanistan,Production,Riz et produits,Milliers de tonnes,338.00
15,Afghanistan,Importations - Quantité,Riz et produits,Milliers de tonnes,415.00
16,Afghanistan,Exportations - Quantité,Riz et produits,Milliers de tonnes,0.00
17,Afghanistan,Disponibilité intérieure,Riz et produits,Milliers de tonnes,753.00
18,Afghanistan,Aliments pour animaux,Riz et produits,Milliers de tonnes,0.00
19,Afghanistan,Semences,Riz et produits,Milliers de tonnes,11.00
20,Afghanistan,Pertes,Riz et produits,Milliers de tonnes,24.00
21,Afghanistan,Résidus,Riz et produits,Milliers de tonnes,0.00
22,Afghanistan,Nourriture,Riz et produits,Milliers de tonnes,717.00
23,Afghanistan,Disponibilité alimentaire en quantité (kg/pers...,Riz et produits,kg,19.77
24,Afghanistan,Disponibilité alimentaire (Kcal/personne/jour),Riz et produits,Kcal/personne/jour,135.00
25,Afghanistan,Disponibilité de protéines en quantité (g/pers...,Riz et produits,g/personne/jour,2.58
26,Afghanistan,Disponibilité de matière grasse en quantité (g...,Riz et produits,g/personne/jour,0.25
27,Afghanistan,Production,Orge et produits,Milliers de tonnes,95.00
28,Afghanistan,Importations - Quantité,Orge et produits,Milliers de tonnes,15.00
29,Afghanistan,Variation de stock,Orge et produits,Milliers de tonnes,0.00

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Colonne 'Produit'</h3>
</div>

In [7]:
# Affiche la liste des valeurs uniques de la colonne 'Zone'
for element in df_dispoali_2017_clean["Produit"].unique():
    print(element)

Blé et produits
Riz et produits
Orge et produits
Maïs et produits
Seigle et produits
Avoine
Millet et produits
Sorgho et produits
Céréales, Autres
Pommes de Terre et produits
Ignames
Racines nda
Sucre, canne
Sucre, betterave
Sucre Eq Brut
Edulcorants Autres
Miel
Haricots
Pois
Légumineuses Autres et produits
Noix et produits
Soja
Arachides Decortiquees
Graines de tournesol
Graines Colza/Moutarde
Graines de coton
Coco (Incl Coprah)
Sésame
Olives
Plantes Oleiferes, Autre
Huile de Soja
Huile d'Arachide
Huile de Tournesol
Huile de Colza&Moutarde
Huile Graines de Coton
Huile de Palmistes
Huile de Palme
Huile de Coco
Huile de Sésame
Huile d'Olive
Huile de Son de Riz
Huile de Germe de Maïs
Huil Plantes Oleif Autr
Tomates et produits
Oignons
Légumes, Autres
Oranges, Mandarines
Citrons & Limes et produits
Pamplemousse et produits
Agrumes, Autres
Bananes
Pommes et produits
Ananas et produits
Dattes
Raisin
Fruits, Autres
Café et produits
Feve de Cacao et produits
Thé
Poivre
Piments
Girofles
Épices, Autres
Vin
Bière
Boissons Fermentés
Boissons Alcooliques
Alcool, non Comestible
Viande de Bovins
Viande d'Ovins/Caprins
Viande de Suides
Viande de Volailles
Viande, Autre
Abats Comestible
Beurre, Ghee
Crème
Graisses Animales Crue
Oeufs
Lait - Excl Beurre
Poissons Eau Douce
Aliments pour enfants
Miscellanees
Manioc et produits
Patates douces
Palmistes
Bananes plantains
Huiles de Poissons
Huiles de Foie de Poisso
Perciform
Poissons Pelagiques
Poissons Marins, Autres
Crustacés
Cephalopodes
Mollusques, Autres
Animaux Aquatiques Autre
Plantes Aquatiques
Sucre non centrifugé
Viande de Anim Aquatiq

In [8]:
df_dispoali_2017_clean = df_dispoali_2017_clean[df_dispoali_2017_clean['Produit'].isin(["Viande de Volailles"])]

#Il ne reste plus que la 'viande de volailles' donc on supprime les colonnes qui deviennent inutiles
df_dispoali_2017_clean.drop(columns=["Produit"], inplace=True)

display(df_dispoali_2017_clean)

,Zone,Élément,Unité,Valeur
651,Afghanistan,Production,Milliers de tonnes,28.00
652,Afghanistan,Importations - Quantité,Milliers de tonnes,29.00
653,Afghanistan,Variation de stock,Milliers de tonnes,0.00
654,Afghanistan,Disponibilité intérieure,Milliers de tonnes,57.00
655,Afghanistan,Pertes,Milliers de tonnes,2.00
...,...,...,...,...
176396,Zimbabwe,Nourriture,Milliers de tonnes,67.00
176397,Zimbabwe,Disponibilité alimentaire en quantité (kg/pers...,kg,4.68
176398,Zimbabwe,Disponibilité alimentaire (Kcal/personne/jour),Kcal/personne/jour,16.00
176399,Zimbabwe,Disponibilité de protéines en quantité (g/pers...,g/personne/jour,1.59
176400,Zimbabwe,Disponibilité de matière grasse en quantité (g...,g/personne/jour,0.99

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Colonne 'Élément'</h3>
</div>

In [9]:
# Affiche la liste des valeurs uniques de la colonne 'Zone'
for element in df_dispoali_2017_clean["Élément"].unique():
    print(element)

Production
Importations - Quantité
Variation de stock
Disponibilité intérieure
Pertes
Résidus
Nourriture
Disponibilité alimentaire en quantité (kg/personne/an)
Disponibilité alimentaire (Kcal/personne/jour)
Disponibilité de protéines en quantité (g/personne/jour)
Disponibilité de matière grasse en quantité (g/personne/jour)
Exportations - Quantité
Alimentation pour touristes
Traitement
Autres utilisations (non alimentaire)
Aliments pour animaux
Semences

In [10]:
#Filtre les éléments voulus de la colonne 'Élément'                    
df_dispoali_2017_clean = df_dispoali_2017_clean[df_dispoali_2017_clean['Élément'].isin(["Production",
                                                                                        "Importations - Quantité",
                                                                                        "Exportations - Quantité",
                                                                                        "Disponibilité intérieure",
                                                                                        "Disponibilité alimentaire en quantité (kg/personne/an)"])]

display(df_dispoali_2017_clean)

,Zone,Élément,Unité,Valeur
651,Afghanistan,Production,Milliers de tonnes,28.00
652,Afghanistan,Importations - Quantité,Milliers de tonnes,29.00
654,Afghanistan,Disponibilité intérieure,Milliers de tonnes,57.00
658,Afghanistan,Disponibilité alimentaire en quantité (kg/pers...,kg,1.53
1704,Afrique du Sud,Production,Milliers de tonnes,1667.00
...,...,...,...,...
175370,Zambie,Disponibilité alimentaire en quantité (kg/pers...,kg,3.42
176388,Zimbabwe,Production,Milliers de tonnes,69.00
176389,Zimbabwe,Importations - Quantité,Milliers de tonnes,6.00
176391,Zimbabwe,Disponibilité intérieure,Milliers de tonnes,76.00
176397,Zimbabwe,Disponibilité alimentaire en quantité (kg/pers...,kg,4.68

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Pivot</h3>
</div>

In [11]:
# Pivot - On bascule les lignes du format "Long" au format "Large"

df_dispoali_2017_clean_pivot = df_dispoali_2017_clean.pivot_table(    ### p=production, x=exportation, m=importation
    index='Zone',                    # Une seule ligne par pays (Zone)
    columns='Élément',               # Les 3 éléments deviennent les 3 nouvelles colonnes
    values='Valeur',                 # On remplit avec les chiffres de la colonne Valeur
    aggfunc='sum'                    # Sécurité en cas de doublons (fait la somme)
).reset_index()                      # Permet de transformer 'Zone' en vraie colonne exploitable

# Nettoyage final du nom des colonnes
df_dispoali_2017_clean_pivot.columns.name = None

display(df_dispoali_2017_clean_pivot.head())

# Compte le nombre total de lignes contenant une parenthèse ouvrante ou fermante
nb_lignes = (
    df_dispoali_2017_clean["Zone"]
    .str.contains(r"[\(\)]", regex=True, na=False)
    .sum()
)
print(f"Il y a {nb_lignes} lignes avec des parenthèses.")

# Filtre les lignes qui contiennent des parenthèses dans la colonne Zone
mask = df_dispoali_2017_clean["Zone"].str.contains(
    r"[\(\)]", regex=True, na=False
)

# Extrait les valeurs uniques de ces lignes et on les affiche sous forme de liste
valeurs_uniques_parentheses = (
    df_dispoali_2017_clean.loc[mask, "Zone"].unique().tolist()
)

print(valeurs_uniques_parentheses)

# Compte le nombre total de lignes contenant une parenthèse ouvrante ou fermante
nb_lignes = (
    df_dispoali_2017_clean["Zone"]
    .str.contains(r"[\(\)]", regex=True, na=False)
    .sum()
)
print(f"Il y a {nb_lignes} lignes avec des parenthèses.")

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Production
0,Afghanistan,1.53,57.0,NaN,29.0,28.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0
2,Albanie,16.36,47.0,0.0,38.0,13.0
3,Algérie,6.38,277.0,0.0,2.0,275.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0

Il y a 15 lignes avec des parenthèses.
['Bolivie (État plurinational de)', "Iran (République islamique d')", 'Venezuela (République bolivarienne du)']
Il y a 15 lignes avec des parenthèses.

In [12]:
#Renommage des colonnes
df_dispoali_2017_clean_pivot.columns = ['Zone',
                                        'Disponibilité alimentaire en quantité (kg/personne/an)',
                                        'Disponibilité intérieure (en milliers de tonnes)',
                                        'Exportations - Quantité (en milliers de tonnes)',
                                        'Importations - Quantité (en milliers de tonnes)',
                                        'Production (en milliers de tonnes)']
display(df_dispoali_2017_clean_pivot)

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes)
0,Afghanistan,1.53,57.0,NaN,29.0,28.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0
2,Albanie,16.36,47.0,0.0,38.0,13.0
3,Algérie,6.38,277.0,0.0,2.0,275.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0
...,...,...,...,...,...,...
167,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0
168,Équateur,19.31,341.0,0.0,0.0,340.0
169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0
170,Éthiopie,0.13,14.0,NaN,1.0,14.0
171,Îles Salomon,4.45,3.0,0.0,6.0,0.0

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Inspection fin</h3>
</div>

In [13]:
from mes_fonctions import inspector
inspector(df_dispoali_2017_clean_pivot)

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 172 ; Nb de colonnes: 6

----------------------
Types de données:
Zone                                                       object
Disponibilité alimentaire en quantité (kg/personne/an)    float64
Disponibilité intérieure (en milliers de tonnes)          float64
Exportations - Quantité (en milliers de tonnes)           float64
Importations - Quantité (en milliers de tonnes)           float64
Production (en milliers de tonnes)                        float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Zone                                                      172
Disponibilité alimentaire en quantité (kg/personne/an)    169
Disponibilité intérieure (en milliers de tonnes)          135
Exportations - Quantité (en milliers de tonnes)            50
Importations - Quantité (en milliers de tonnes)            84
Production (en milliers de tonnes)                        125
dtype: int64

----------------------
Valeurs manquantes:
Zone                                                       0
Disponibilité alimentaire en quantité (kg/personne/an)     0
Disponibilité intérieure (en milliers de tonnes)           2
Exportations - Quantité (en milliers de tonnes)           37
Importations - Quantité (en milliers de tonnes)            2
Production (en milliers de tonnes)                         4
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes)
0,Afghanistan,1.53,57.0,NaN,29.0,28.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0
2,Albanie,16.36,47.0,0.0,38.0,13.0
3,Algérie,6.38,277.0,0.0,2.0,275.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0
...,...,...,...,...,...,...
167,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0
168,Équateur,19.31,341.0,0.0,0.0,340.0
169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0
170,Éthiopie,0.13,14.0,NaN,1.0,14.0
171,Îles Salomon,4.45,3.0,0.0,6.0,0.0

##############################################################################

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">NAN</h3>
</div>

In [14]:
# Compte le nombre total de lignes ayant au moins un NaN
nb_lignes_avec_nan_dispoali = df_dispoali_2017_clean_pivot.isna().any(axis=1).sum()

print(f"Nombre de lignes avec au moins un NaN : {nb_lignes_avec_nan_dispoali}")

Nombre de lignes avec au moins un NaN : 37

In [15]:
# Affiche uniquement les colonnes avec des NaN, de la plus vide à la moins vide
df_dispoali_2017_clean_pivot.isna().sum()[df_dispoali_2017_clean_pivot.isna().sum() > 0].sort_values(ascending=False)

Exportations - Quantité (en milliers de tonnes)     37
Production (en milliers de tonnes)                   4
Disponibilité intérieure (en milliers de tonnes)     2
Importations - Quantité (en milliers de tonnes)      2
dtype: int64

In [16]:
df_dispoali_2017_clean_pivot[df_dispoali_2017_clean_pivot['Exportations - Quantité (en milliers de tonnes)'].isna()]

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes)
0,Afghanistan,1.53,57.0,NaN,29.0,28.0
13,Bahamas,43.17,26.0,NaN,24.0,6.0
14,Bangladesh,1.50,250.0,NaN,0.0,249.0
23,Burkina Faso,2.27,46.0,NaN,0.0,46.0
26,Cabo Verde,17.62,10.0,NaN,12.0,1.0
27,Cambodge,2.34,38.0,NaN,10.0,28.0
40,Cuba,23.72,342.0,NaN,312.0,29.0
43,Djibouti,2.68,3.0,NaN,3.0,NaN
54,Gambie,3.53,8.0,NaN,16.0,2.0
56,Grenade,45.70,8.0,NaN,7.0,1.0
59,Guinée,4.08,50.0,NaN,37.0,13.0
60,Guinée-Bissau,2.16,4.0,NaN,4.0,3.0
63,Haïti,8.91,98.0,NaN,89.0,9.0
80,Kiribati,17.98,2.0,NaN,1.0,1.0
89,Madagascar,2.87,82.0,NaN,0.0,81.0
91,Malawi,5.17,98.0,NaN,0.0,130.0
92,Maldives,13.50,12.0,NaN,12.0,NaN
93,Mali,2.83,52.0,NaN,1.0,48.0
97,Mauritanie,5.14,22.0,NaN,24.0,5.0
99,Mongolie,2.77,9.0,NaN,10.0,0.0
101,Mozambique,3.59,116.0,NaN,24.0,92.0
108,Nouvelle-Calédonie,38.71,11.0,NaN,9.0,1.0
110,Népal,1.99,58.0,NaN,0.0,58.0
113,Ouzbékistan,1.96,NaN,NaN,NaN,NaN
126,République centrafricaine,2.29,11.0,NaN,4.0,7.0
130,République démocratique populaire lao,10.91,NaN,NaN,NaN,NaN
132,République-Unie de Tanzanie,1.88,108.0,NaN,2.0,105.0
134,Saint-Vincent-et-les Grenadines,72.31,8.0,NaN,9.0,0.0
135,Sainte-Lucie,56.69,11.0,NaN,10.0,1.0
137,Sao Tomé-et-Principe,9.47,2.0,NaN,2.0,1.0
142,Soudan,1.60,69.0,NaN,2.0,67.0
148,Tadjikistan,4.45,40.0,NaN,38.0,2.0
152,Timor-Leste,4.24,5.0,NaN,11.0,1.0
156,Turkménistan,4.52,27.0,NaN,9.0,20.0
160,Vanuatu,11.66,3.0,NaN,4.0,1.0
165,Zimbabwe,4.68,76.0,NaN,6.0,69.0
170,Éthiopie,0.13,14.0,NaN,1.0,14.0

In [17]:
# Remplacement des NaN par 0 uniquement dans la colonne 'Exportations - Quantité (en milliers de tonnes)'
# Je pars du principe qu'il n'exporte pas de poulet si la valeur est 'Nan'
# En effet, la disponibilité intérieur est souvent proche voir égal à la somme de la production intérieur et de l'importation
df_dispoali_2017_clean_pivot.loc[df_dispoali_2017_clean_pivot['Exportations - Quantité (en milliers de tonnes)']
    .isna(), 'Exportations - Quantité (en milliers de tonnes)'] = 0

In [18]:
df_dispoali_2017_clean_pivot[df_dispoali_2017_clean_pivot['Exportations - Quantité (en milliers de tonnes)'].isna()]

Empty DataFrame
Columns: [Zone, Disponibilité alimentaire en quantité (kg/personne/an), Disponibilité intérieure (en milliers de tonnes), Exportations - Quantité (en milliers de tonnes), Importations - Quantité (en milliers de tonnes), Production (en milliers de tonnes)]
Index: []

In [19]:
df_dispoali_2017_clean_pivot[df_dispoali_2017_clean_pivot['Production (en milliers de tonnes)'].isna()]

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes)
43,Djibouti,2.68,3.0,0.0,3.0,NaN
92,Maldives,13.50,12.0,0.0,12.0,NaN
113,Ouzbékistan,1.96,NaN,0.0,NaN,NaN
130,République démocratique populaire lao,10.91,NaN,0.0,NaN,NaN

In [20]:
# Je choisis de remplacer les NaN par 0 pour 'Djibouti' et 'Maldives car la colonne 'Disponibilité intérieur' = 'Importations'
# Je pars du principe que si 'Disponibilité intérieur' = 'Importations' alors ils ne produisent pas sur leur territoire 
df_dispoali_2017_clean_pivot.loc[
    df_dispoali_2017_clean_pivot['Zone'].isin(['Djibouti', 'Maldives']) & 
    df_dispoali_2017_clean_pivot['Production (en milliers de tonnes)'].isna(), 
    'Production (en milliers de tonnes)'
] = 0

# Vérifier modifications
# Filtre sur la colonne 'Zone' et sélectionne la colonne de production
display(df_dispoali_2017_clean_pivot.loc[
    df_dispoali_2017_clean_pivot['Zone'].isin(['Djibouti', 'Maldives']), 
    ['Zone', 'Production (en milliers de tonnes)']
])

# Affiche toutes les colonnes de 'Djibouti' et 'Maldives' pour vérifiactions
with pd.option_context("display.max_columns", None):
    # 2. On affiche la ligne complète pour Djibouti et les Maldives
    display(
        df_dispoali_2017_clean_pivot[
            df_dispoali_2017_clean_pivot["Zone"].isin(["Djibouti", "Maldives"])
        ]
    )

# Je choisis de supprimer les 2 lignes comportants plusieurs 'Nan' en plus de la production
# En effet, l'Ouzbékistan et la République démocratique populaire lao comporte des 'Nan' dans d'autres colonnes
# La production est un élément important pour savoir s'il y a de la concurrence ou pas

# Supprime les lignes où la colonne 'Production (en milliers de tonnes)' contient un NaN
df_dispoali_2017_clean_pivot.dropna(subset=['Production (en milliers de tonnes)'], inplace=True)

        Zone  Production (en milliers de tonnes)
43  Djibouti                                 0.0
92  Maldives                                 0.0

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes)
43,Djibouti,2.68,3.0,0.0,3.0,0.0
92,Maldives,13.50,12.0,0.0,12.0,0.0

In [21]:
df_dispoali_2017_clean_pivot[df_dispoali_2017_clean_pivot['Production (en milliers de tonnes)'].isna()]

Empty DataFrame
Columns: [Zone, Disponibilité alimentaire en quantité (kg/personne/an), Disponibilité intérieure (en milliers de tonnes), Exportations - Quantité (en milliers de tonnes), Importations - Quantité (en milliers de tonnes), Production (en milliers de tonnes)]
Index: []

In [22]:
# Affiche les NaN de la colonne 'Disponibilité intérieure (en milliers de tonnes)'
df_dispoali_2017_clean_pivot[df_dispoali_2017_clean_pivot['Disponibilité intérieure (en milliers de tonnes)'].isna()]

Empty DataFrame
Columns: [Zone, Disponibilité alimentaire en quantité (kg/personne/an), Disponibilité intérieure (en milliers de tonnes), Exportations - Quantité (en milliers de tonnes), Importations - Quantité (en milliers de tonnes), Production (en milliers de tonnes)]
Index: []

In [23]:
# Les deux pays qui avait une ligne comportant des 'Nan' était l'Ouzbékistan et de la République démocratique populaire lao qui ont été supprimé précédemment

In [24]:
#Affiche les NaN de la colonne 'Importations - Quantité (en milliers de tonnes)'
df_dispoali_2017_clean_pivot[df_dispoali_2017_clean_pivot['Importations - Quantité (en milliers de tonnes)'].isna()]

Empty DataFrame
Columns: [Zone, Disponibilité alimentaire en quantité (kg/personne/an), Disponibilité intérieure (en milliers de tonnes), Exportations - Quantité (en milliers de tonnes), Importations - Quantité (en milliers de tonnes), Production (en milliers de tonnes)]
Index: []

In [25]:
# Les deux pays qui avait une ligne comportant des 'Nan' était l'Ouzbékistan et de la République démocratique populaire lao qui ont été supprimé précédemment

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Zone avec parenthèses</h3>
</div>

In [26]:
# Filtre les lignes qui contiennent des parenthèses dans la colonne 'Zone'
mask = df_dispoali_2017_clean_pivot["Zone"].str.contains(
    r"[\(\)]", regex=True, na=False)

#Extraction des valeurs uniques du mask pour les afficher sous forme de liste
valeurs_uniques_parentheses = (
    df_dispoali_2017_clean_pivot.loc[mask, "Zone"].unique().tolist())

print(valeurs_uniques_parentheses)

#Enlève les éléments entre parenthèse dans la colonne 'Zone'
df_dispoali_2017_clean_pivot['Zone'] = df_dispoali_2017_clean_pivot['Zone'].str.replace(r'\s*\(.*\)', '', regex=True)

# --- verif modifications ---
mask = df_dispoali_2017_clean_pivot["Zone"].str.contains(
    r"[\(\)]", regex=True, na=False)

valeurs_uniques_parentheses = (
    df_dispoali_2017_clean_pivot.loc[mask, "Zone"].unique().tolist())

print(valeurs_uniques_parentheses)

display(df_dispoali_2017_clean_pivot)

['Bolivie (État plurinational de)', "Iran (République islamique d')", 'Venezuela (République bolivarienne du)']
[]

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes)
0,Afghanistan,1.53,57.0,0.0,29.0,28.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0
2,Albanie,16.36,47.0,0.0,38.0,13.0
3,Algérie,6.38,277.0,0.0,2.0,275.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0
...,...,...,...,...,...,...
167,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0
168,Équateur,19.31,341.0,0.0,0.0,340.0
169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0
170,Éthiopie,0.13,14.0,0.0,1.0,14.0
171,Îles Salomon,4.45,3.0,0.0,6.0,0.0

In [27]:
from mes_fonctions import inspector
inspector(df_dispoali_2017_clean_pivot)

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 170 ; Nb de colonnes: 6

----------------------
Types de données:
Zone                                                       object
Disponibilité alimentaire en quantité (kg/personne/an)    float64
Disponibilité intérieure (en milliers de tonnes)          float64
Exportations - Quantité (en milliers de tonnes)           float64
Importations - Quantité (en milliers de tonnes)           float64
Production (en milliers de tonnes)                        float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Zone                                                      170
Disponibilité alimentaire en quantité (kg/personne/an)    167
Disponibilité intérieure (en milliers de tonnes)          135
Exportations - Quantité (en milliers de tonnes)            50
Importations - Quantité (en milliers de tonnes)            84
Production (en milliers de tonnes)                        125
dtype: int64

----------------------
Valeurs manquantes:
Zone                                                      0
Disponibilité alimentaire en quantité (kg/personne/an)    0
Disponibilité intérieure (en milliers de tonnes)          0
Exportations - Quantité (en milliers de tonnes)           0
Importations - Quantité (en milliers de tonnes)           0
Production (en milliers de tonnes)                        0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes)
0,Afghanistan,1.53,57.0,0.0,29.0,28.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0
2,Albanie,16.36,47.0,0.0,38.0,13.0
3,Algérie,6.38,277.0,0.0,2.0,275.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0
...,...,...,...,...,...,...
167,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0
168,Équateur,19.31,341.0,0.0,0.0,340.0
169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0
170,Éthiopie,0.13,14.0,0.0,1.0,14.0
171,Îles Salomon,4.45,3.0,0.0,6.0,0.0

##############################################################################

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2.2 - Nettoyage - 'Population_2000_2018.csv' -> df_pop_2017_clean</h2>
</div>

<div style="border: 1px solid RGB(150, 20, 30); padding: 20px;">
    <h3 style="margin: 0; color: RGB(0, 50, 230); line-height: 1.6;">
        Variable :<br>
        • Population
    </h3>
</div>

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Inspection</h3>
</div>

In [28]:
# --- Nettoyage ---
df_pop_clean = df_pop.copy()
print("📊 --- ÉTAT INITIAL ---")

from mes_fonctions import inspector
inspector(df_pop_clean)

📊 --- ÉTAT INITIAL ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 4411 ; Nb de colonnes: 15

----------------------
Types de données:
Code Domaine               object
Domaine                    object
Code zone                   int64
Zone                       object
Code Élément                int64
Élément                    object
Code Produit                int64
Produit                    object
Code année                  int64
Année                       int64
Unité                      object
Valeur                    float64
Symbole                    object
Description du Symbole     object
Note                       object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Code Domaine                 1
Domaine                      1
Code zone                  238
Zone                       238
Code Élément                 1
Élément                      1
Code Produit                 1
Produit                      1
Code année                  19
Année                       19
Unité                        1
Valeur                    4398
Symbole                      2
Description du Symbole       2
Note                         1
dtype: int64

----------------------
Valeurs manquantes:
Code Domaine                 0
Domaine                      0
Code zone                    0
Zone                         0
Code Élément                 0
Élément                      0
Code Produit                 0
Produit                      0
Code année                   0
Année                        0
Unité                        0
Valeur                       0
Symbole                      0
Description du Symbole       0
Note                      4153
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2000,2000,1000 personnes,20779.953,X,Sources internationales sûres,NaN
1,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2001,2001,1000 personnes,21606.988,X,Sources internationales sûres,NaN
2,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2002,2002,1000 personnes,22600.770,X,Sources internationales sûres,NaN
3,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2003,2003,1000 personnes,23680.871,X,Sources internationales sûres,NaN
4,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2004,2004,1000 personnes,24726.684,X,Sources internationales sûres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4406,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2014,2014,1000 personnes,13586.707,X,Sources internationales sûres,NaN
4407,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2015,2015,1000 personnes,13814.629,X,Sources internationales sûres,NaN
4408,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2016,2016,1000 personnes,14030.331,X,Sources internationales sûres,NaN
4409,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,14236.595,X,Sources internationales sûres,NaN
4410,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2018,2018,1000 personnes,14438.802,X,Sources internationales sûres,NaN

##############################################################################

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Nom des colonnes et suppression</h3>
</div>

In [29]:
nom_colonnes_df_pop_clean = df_pop_clean.columns

for colonne_df_pop in nom_colonnes_df_pop_clean:
    print(colonne_df_pop)
display(df_pop_clean)

Code Domaine
Domaine
Code zone
Zone
Code Élément
Élément
Code Produit
Produit
Code année
Année
Unité
Valeur
Symbole
Description du Symbole
Note

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2000,2000,1000 personnes,20779.953,X,Sources internationales sûres,NaN
1,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2001,2001,1000 personnes,21606.988,X,Sources internationales sûres,NaN
2,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2002,2002,1000 personnes,22600.770,X,Sources internationales sûres,NaN
3,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2003,2003,1000 personnes,23680.871,X,Sources internationales sûres,NaN
4,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2004,2004,1000 personnes,24726.684,X,Sources internationales sûres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4406,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2014,2014,1000 personnes,13586.707,X,Sources internationales sûres,NaN
4407,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2015,2015,1000 personnes,13814.629,X,Sources internationales sûres,NaN
4408,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2016,2016,1000 personnes,14030.331,X,Sources internationales sûres,NaN
4409,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,14236.595,X,Sources internationales sûres,NaN
4410,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2018,2018,1000 personnes,14438.802,X,Sources internationales sûres,NaN

In [30]:
# Supprimer colonnes non importante
# On ne garde que les colonnes 'Zone', 'Année', 'Valeur'
df_pop_clean = df_pop_clean[['Zone', 'Année', 'Valeur']]

# On multiplie la colone 'population' par 1000 pour avoir la population
df_pop_clean['Valeur'] = df_pop_clean['Valeur']*1000

display(df_pop_clean.head(30))

              Zone  Année      Valeur
0      Afghanistan   2000  20779953.0
1      Afghanistan   2001  21606988.0
2      Afghanistan   2002  22600770.0
3      Afghanistan   2003  23680871.0
4      Afghanistan   2004  24726684.0
5      Afghanistan   2005  25654277.0
6      Afghanistan   2006  26433049.0
7      Afghanistan   2007  27100536.0
8      Afghanistan   2008  27722276.0
9      Afghanistan   2009  28394813.0
10     Afghanistan   2010  29185507.0
11     Afghanistan   2011  30117413.0
12     Afghanistan   2012  31161376.0
13     Afghanistan   2013  32269589.0
14     Afghanistan   2014  33370794.0
15     Afghanistan   2015  34413603.0
16     Afghanistan   2016  35383032.0
17     Afghanistan   2017  36296113.0
18     Afghanistan   2018  37171921.0
19  Afrique du Sud   2000  44967708.0
20  Afrique du Sud   2001  45571274.0
21  Afrique du Sud   2002  46150913.0
22  Afrique du Sud   2003  46719196.0
23  Afrique du Sud   2004  47291610.0
24  Afrique du Sud   2005  47880601.0
25  Afrique du Sud   2006  48489459.0
26  Afrique du Sud   2007  49119759.0
27  Afrique du Sud   2008  49779471.0
28  Afrique du Sud   2009  50477011.0
29  Afrique du Sud   2010  51216964.0

In [31]:
# On ne garde que les valeurs de 2017
df_pop_clean = df_pop_clean[df_pop_clean["Année"] == 2017]

# Il ne reste plus que l'année 2017 donc on supprime la colonne année qui devient inutile
df_pop_clean.drop(columns=["Année"], inplace=True)

# Renommage des colonnes
df_pop_clean.columns = ["Zone", "Population"]

df_pop_2017_clean = df_pop_clean

display(df_pop_2017_clean)

                                        Zone  Population
17                               Afghanistan  36296113.0
36                            Afrique du Sud  57009756.0
55                                   Albanie   2884169.0
74                                   Algérie  41389189.0
93                                 Allemagne  82658409.0
...                                      ...         ...
4333  Venezuela (République bolivarienne du)  29402484.0
4352                                Viet Nam  94600648.0
4371                                   Yémen  27834819.0
4390                                  Zambie  16853599.0
4409                                Zimbabwe  14236595.0

[236 rows x 2 columns]

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">NAN</h3>
</div>

In [32]:
# Compte le nombre total de lignes ayant au moins un NaN
nb_lignes_avec_nan_pop_2017 = df_pop_2017_clean.isna().any(axis=1).sum()

print(f"Nombre de lignes avec au moins un NaN : {nb_lignes_avec_nan_pop_2017}")

Nombre de lignes avec au moins un NaN : 0

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Zone avec parenthèses</h3>
</div>

In [33]:
# Valeurs avec parenthèse ?
# Filtre pour les lignes qui contiennent des parenthèses dans la colonne 'Zone'
mask = df_pop_2017_clean["Zone"].str.contains(
    r"[\(\)]", regex=True, na=False)

# Extraction des valeurs uniques du mask pour les afficher sous forme de liste
valeurs_uniques_parentheses = (
    df_pop_2017_clean.loc[mask, "Zone"].unique().tolist())

print(valeurs_uniques_parentheses)


# Enlève les éléments entre parenthèse dans la colonne 'Zone'
df_pop_2017_clean['Zone'] = df_pop_2017_clean['Zone'].str.replace(r'\s*\(.*\)', '', regex=True)

# Vérifie modifications
mask = df_pop_2017_clean["Zone"].str.contains(
    r"[\(\)]", regex=True, na=False)

valeurs_uniques_parentheses = (
    df_pop_2017_clean.loc[mask, "Zone"].unique().tolist())

print(valeurs_uniques_parentheses)

display(df_pop_2017_clean)

['Antilles néerlandaises (ex)', 'Bolivie (État plurinational de)', 'Îles Falkland (Malvinas)', "Iran (République islamique d')", 'Micronésie (États fédérés de)', 'Saint-Martin (partie française)', 'Sint Maarten  (partie néerlandaise)', 'Venezuela (République bolivarienne du)']
[]

                Zone  Population
17       Afghanistan  36296113.0
36    Afrique du Sud  57009756.0
55           Albanie   2884169.0
74           Algérie  41389189.0
93         Allemagne  82658409.0
...              ...         ...
4333       Venezuela  29402484.0
4352        Viet Nam  94600648.0
4371           Yémen  27834819.0
4390          Zambie  16853599.0
4409        Zimbabwe  14236595.0

[236 rows x 2 columns]

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Inspection fin</h3>
</div>

In [34]:
from mes_fonctions import inspector
inspector(df_pop_2017_clean)

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 236 ; Nb de colonnes: 2

----------------------
Types de données:
Zone           object
Population    float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Zone          236
Population    236
dtype: int64

----------------------
Valeurs manquantes:
Zone          0
Population    0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

                Zone  Population
17       Afghanistan  36296113.0
36    Afrique du Sud  57009756.0
55           Albanie   2884169.0
74           Algérie  41389189.0
93         Allemagne  82658409.0
...              ...         ...
4333       Venezuela  29402484.0
4352        Viet Nam  94600648.0
4371           Yémen  27834819.0
4390          Zambie  16853599.0
4409        Zimbabwe  14236595.0

[236 rows x 2 columns]

##############################################################################

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2.3 - Nettoyage - 'PIB_2017_en_USD' -> df_pib_2017_clean</h2>
</div>

<div style="border: 1px solid RGB(150, 20, 30); padding: 20px;">
    <h3 style="margin: 0; color: RGB(0, 50, 230); line-height: 1.6;">
        Variables :<br>
        • PIB
    </h3>
</div>

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Inspection</h3>
</div>

In [35]:
# --- Nettoyage ---
df_pib_2017_clean = df_pib_2017.copy()
print("📊 --- ÉTAT INITIAL ---")

from mes_fonctions import inspector
inspector(df_pib_2017_clean)

📊 --- ÉTAT INITIAL ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 210 ; Nb de colonnes: 15

----------------------
Types de données:
Code Domaine               object
Domaine                    object
Code zone (M49)             int64
Zone                       object
Code Élément                int64
Élément                    object
Code Produit                int64
Produit                    object
Code année                  int64
Année                       int64
Unité                      object
Valeur                    float64
Symbole                    object
Description du Symbole     object
Note                      float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Code Domaine                1
Domaine                     1
Code zone (M49)           210
Zone                      210
Code Élément                1
Élément                     1
Code Produit                1
Produit                     1
Code année                  1
Année                       1
Unité                       1
Valeur                    210
Symbole                     1
Description du Symbole      1
Note                        0
dtype: int64

----------------------
Valeurs manquantes:
Code Domaine                0
Domaine                     0
Code zone (M49)             0
Zone                        0
Code Élément                0
Élément                     0
Code Produit                0
Produit                     0
Code année                  0
Année                       0
Unité                       0
Valeur                      0
Symbole                     0
Description du Symbole      0
Note                      210
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,MK,Indicateurs macro,4,Afghanistan,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,1.903430e+04,X,Chiffre de source externe,NaN
1,MK,Indicateurs macro,710,Afrique du Sud,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,3.811367e+05,X,Chiffre de source externe,NaN
2,MK,Indicateurs macro,8,Albanie,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,1.301973e+04,X,Chiffre de source externe,NaN
3,MK,Indicateurs macro,12,Algérie,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,1.700970e+05,X,Chiffre de source externe,NaN
4,MK,Indicateurs macro,276,Allemagne,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,3.763092e+06,X,Chiffre de source externe,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,MK,Indicateurs macro,862,Venezuela (République bolivarienne du),6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,2.470511e+05,X,Chiffre de source externe,NaN
206,MK,Indicateurs macro,704,Viet Nam,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,2.813536e+05,X,Chiffre de source externe,NaN
207,MK,Indicateurs macro,887,Yémen,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,1.839165e+04,X,Chiffre de source externe,NaN
208,MK,Indicateurs macro,894,Zambie,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,2.590071e+04,X,Chiffre de source externe,NaN
209,MK,Indicateurs macro,716,Zimbabwe,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,2.204065e+04,X,Chiffre de source externe,NaN

##############################################################################

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Nom des colonnes et suppression</h3>
</div>

In [36]:
nom_colonnes_df_pib_2017_clean = df_pib_2017_clean.columns

for colonne_df_pib in nom_colonnes_df_pib_2017_clean:
    print(colonne_df_pib)
display(df_pib_2017_clean)

Code Domaine
Domaine
Code zone (M49)
Zone
Code Élément
Élément
Code Produit
Produit
Code année
Année
Unité
Valeur
Symbole
Description du Symbole
Note

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,MK,Indicateurs macro,4,Afghanistan,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,1.903430e+04,X,Chiffre de source externe,NaN
1,MK,Indicateurs macro,710,Afrique du Sud,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,3.811367e+05,X,Chiffre de source externe,NaN
2,MK,Indicateurs macro,8,Albanie,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,1.301973e+04,X,Chiffre de source externe,NaN
3,MK,Indicateurs macro,12,Algérie,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,1.700970e+05,X,Chiffre de source externe,NaN
4,MK,Indicateurs macro,276,Allemagne,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,3.763092e+06,X,Chiffre de source externe,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,MK,Indicateurs macro,862,Venezuela (République bolivarienne du),6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,2.470511e+05,X,Chiffre de source externe,NaN
206,MK,Indicateurs macro,704,Viet Nam,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,2.813536e+05,X,Chiffre de source externe,NaN
207,MK,Indicateurs macro,887,Yémen,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,1.839165e+04,X,Chiffre de source externe,NaN
208,MK,Indicateurs macro,894,Zambie,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,2.590071e+04,X,Chiffre de source externe,NaN
209,MK,Indicateurs macro,716,Zimbabwe,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,2.204065e+04,X,Chiffre de source externe,NaN

In [37]:
#On ne garde que les colonnes 'Zone', 'Valeur'
df_pib_2017_clean = df_pib_2017_clean[['Zone', 'Valeur']]

#Renommage des colonnes
df_pib_2017_clean.columns = ['Zone', "PIB (en millions d'USD)"]

display(df_pib_2017_clean)

                                       Zone  PIB (en millions d'USD)
0                               Afghanistan             1.903430e+04
1                            Afrique du Sud             3.811367e+05
2                                   Albanie             1.301973e+04
3                                   Algérie             1.700970e+05
4                                 Allemagne             3.763092e+06
..                                      ...                      ...
205  Venezuela (République bolivarienne du)             2.470511e+05
206                                Viet Nam             2.813536e+05
207                                   Yémen             1.839165e+04
208                                  Zambie             2.590071e+04
209                                Zimbabwe             2.204065e+04

[210 rows x 2 columns]

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Zone avec parenthèses</h3>
</div>

In [38]:
##Valeurs avec parenthèse ?
#Filtre pour les lignes qui contiennent des parenthèses dans la colonne 'Zone'
mask = df_pib_2017_clean["Zone"].str.contains(
    r"[\(\)]", regex=True, na=False)

#Extraction des valeurs uniques du mask pour les afficher sous forme de liste
valeurs_uniques_parentheses = (
    df_pib_2017_clean.loc[mask, "Zone"].unique().tolist())

print(valeurs_uniques_parentheses)


#Enlève les éléments entre parenthèse dans la colonne 'Zone'
df_pib_2017_clean['Zone'] = df_pib_2017_clean['Zone'].str.replace(r'\s*\(.*\)', '', regex=True)

# --- verif modifications ---
mask = df_pib_2017_clean["Zone"].str.contains(
    r"[\(\)]", regex=True, na=False)

valeurs_uniques_parentheses = (
    df_pib_2017_clean.loc[mask, "Zone"].unique().tolist())

print(valeurs_uniques_parentheses)

['Bolivie (État plurinational de)', "Iran (République islamique d')", 'Micronésie (États fédérés de)', 'Pays-Bas (Royaume des)', 'Sint Maarten (partie néerlandaise)', 'Venezuela (République bolivarienne du)']
[]

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Inspection fin</h3>
</div>

In [39]:
from mes_fonctions import inspector
inspector(df_pib_2017_clean)

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 210 ; Nb de colonnes: 2

----------------------
Types de données:
Zone                        object
PIB (en millions d'USD)    float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Zone                       210
PIB (en millions d'USD)    210
dtype: int64

----------------------
Valeurs manquantes:
Zone                       0
PIB (en millions d'USD)    0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

               Zone  PIB (en millions d'USD)
0       Afghanistan             1.903430e+04
1    Afrique du Sud             3.811367e+05
2           Albanie             1.301973e+04
3           Algérie             1.700970e+05
4         Allemagne             3.763092e+06
..              ...                      ...
205       Venezuela             2.470511e+05
206        Viet Nam             2.813536e+05
207           Yémen             1.839165e+04
208          Zambie             2.590071e+04
209        Zimbabwe             2.204065e+04

[210 rows x 2 columns]

##############################################################################

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2.4 - Nettoyage - 'Coût_et_abordabilité_d_une_alimentation_saine_(CoAHD)_2017' -> df_cout_ali_saine_2017_clean_pivot</h2>
</div>

<div style="border: 1px solid RGB(150, 20, 30); padding: 20px;">
    <h3 style="margin: 0; color: RGB(0, 50, 230); line-height: 1.6;">
        Variable :<br>
        • Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine, en millions
    </h3>
</div>

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Inspection</h3>
</div>

In [40]:
# --- Nettoyage ---
df_cout_ali_saine_2017_clean = df_cout_ali_saine_2017.copy()
print("📊 --- ÉTAT INITIAL ---")

from mes_fonctions import inspector
inspector(df_cout_ali_saine_2017_clean)

📊 --- ÉTAT INITIAL ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 700 ; Nb de colonnes: 15

----------------------
Types de données:
Code Domaine              object
Domaine                   object
Code zone (ISO3)          object
Zone                      object
Code Élément               int64
Élément                   object
Code Produit               int64
Produit                   object
Code année                 int64
Année                      int64
Édition                   object
Unité                     object
Valeur                    object
Symbole                   object
Description du Symbole    object
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Code Domaine                1
Domaine                     1
Code zone (ISO3)          175
Zone                      175
Code Élément                4
Élément                     1
Code Produit                4
Produit                     4
Code année                  1
Année                       1
Édition                     1
Unité                       4
Valeur                    459
Symbole                     2
Description du Symbole      2
dtype: int64

----------------------
Valeurs manquantes:
Code Domaine               0
Domaine                    0
Code zone (ISO3)           0
Zone                       0
Code Élément               0
Élément                    0
Code Produit               0
Produit                    0
Code année                 0
Année                      0
Édition                    0
Unité                      0
Valeur                    44
Symbole                    0
Description du Symbole     0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Code Domaine,Domaine,Code zone (ISO3),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Édition,Unité,Valeur,Symbole,Description du Symbole
0,CAHD,Coût et abordabilité d’une alimentation saine\...,ZAF,Afrique du Sud,6205,Valeur,70041,"Cost of a healthy diet (CoHD), LCU per person ...",2017,2017,Juillet 2025 (rapport SOFI),UML/personne/jour,19.96,E,Valeur estimée
1,CAHD,Coût et abordabilité d’une alimentation saine\...,ZAF,Afrique du Sud,6226,Valeur,70040,"Cost of a healthy diet (CoHD), PPP dollar per ...",2017,2017,Juillet 2025 (rapport SOFI),Int$ (PPP) per person per day,3,E,Valeur estimée
2,CAHD,Coût et abordabilité d’une alimentation saine\...,ZAF,Afrique du Sud,6121,Valeur,7005,"Prevalence of unaffordability (PUA), percent",2017,2017,Juillet 2025 (rapport SOFI),%,60.8,E,Valeur estimée
3,CAHD,Coût et abordabilité d’une alimentation saine\...,ZAF,Afrique du Sud,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,35,E,Valeur estimée
4,CAHD,Coût et abordabilité d’une alimentation saine\...,ALB,Albanie,6205,Valeur,70041,"Cost of a healthy diet (CoHD), LCU per person ...",2017,2017,Juillet 2025 (rapport SOFI),UML/personne/jour,160.41,E,Valeur estimée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,CAHD,Coût et abordabilité d’une alimentation saine\...,ZMB,Zambie,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,13.6,E,Valeur estimée
696,CAHD,Coût et abordabilité d’une alimentation saine\...,ZWE,Zimbabwe,6205,Valeur,70041,"Cost of a healthy diet (CoHD), LCU per person ...",2017,2017,Juillet 2025 (rapport SOFI),UML/personne/jour,1.68,E,Valeur estimée
697,CAHD,Coût et abordabilité d’une alimentation saine\...,ZWE,Zimbabwe,6226,Valeur,70040,"Cost of a healthy diet (CoHD), PPP dollar per ...",2017,2017,Juillet 2025 (rapport SOFI),Int$ (PPP) per person per day,3.54,E,Valeur estimée
698,CAHD,Coût et abordabilité d’une alimentation saine\...,ZWE,Zimbabwe,6121,Valeur,7005,"Prevalence of unaffordability (PUA), percent",2017,2017,Juillet 2025 (rapport SOFI),%,75.5,E,Valeur estimée
699,CAHD,Coût et abordabilité d’une alimentation saine\...,ZWE,Zimbabwe,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,11.2,E,Valeur estimée

##############################################################################

In [41]:
# La colonne 'Valeur' est de type objet alors qu'elle contient de nombre
# Je vais donc la convertir en nombre pour pour faire des calculs avec cette colonne si besoin

# On repère ce qui devient NaN à la conversion
conversion_nan = pd.to_numeric(df_cout_ali_saine_2017_clean['Valeur'], errors='coerce').isna()

# On exclut les lignes qui étaient déjà vides (NaN) avant la conversion (44 lignes)
# (pour ne cibler que le texte ou les erreurs de saisie)
lignes_non_num_masque = conversion_nan & df_cout_ali_saine_2017_clean['Valeur'].notna()

# On extrait et on affiche toutes les lignes correspondantes
lignes_non_num = df_cout_ali_saine_2017_clean[lignes_non_num_masque]
lignes_non_num_unique = df_cout_ali_saine_2017_clean.loc[lignes_non_num_masque, 'Valeur'].unique()

# Affichage du résultat
print(f"Nombre de lignes problématiques trouvées : {len(lignes_non_num)}")
print(f"Nombre de valeurs non numériques uniques trouvées dans la colonne : {len(lignes_non_num_unique)}")
print(f"Valeurs non numériques uniques trouvées dans la colonne : {lignes_non_num_unique}")
print("")
print("#################################################################################################")
print("")
display(lignes_non_num)

Nombre de lignes problématiques trouvées : 9
Nombre de valeurs non numériques uniques trouvées dans la colonne : 1
Valeurs non numériques uniques trouvées dans la colonne : ['<0.1']

#################################################################################################

,Code Domaine,Domaine,Code zone (ISO3),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Édition,Unité,Valeur,Symbole,Description du Symbole
263,CAHD,Coût et abordabilité d’une alimentation saine\...,GRD,Grenade,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,<0.1,E,Valeur estimée
331,CAHD,Coût et abordabilité d’une alimentation saine\...,ISL,Islande,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,<0.1,E,Valeur estimée
391,CAHD,Coût et abordabilité d’une alimentation saine\...,LUX,Luxembourg,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,<0.1,E,Valeur estimée
411,CAHD,Coût et abordabilité d’une alimentation saine\...,MDV,Maldives,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,<0.1,E,Valeur estimée
419,CAHD,Coût et abordabilité d’une alimentation saine\...,MLT,Malte,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,<0.1,E,Valeur estimée
530,CAHD,Coût et abordabilité d’une alimentation saine\...,QAT,Qatar,6121,Valeur,7005,"Prevalence of unaffordability (PUA), percent",2017,2017,Juillet 2025 (rapport SOFI),%,<0.1,E,Valeur estimée
531,CAHD,Coût et abordabilité d’une alimentation saine\...,QAT,Qatar,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,<0.1,E,Valeur estimée
579,CAHD,Coût et abordabilité d’une alimentation saine\...,LCA,Sainte-Lucie,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,<0.1,E,Valeur estimée
603,CAHD,Coût et abordabilité d’une alimentation saine\...,SYC,Seychelles,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,<0.1,E,Valeur estimée

In [42]:
# Conversion de la colonne 'Valeur' en type numérique
df_cout_ali_saine_2017_clean['Valeur'] = pd.to_numeric(df_cout_ali_saine_2017_clean['Valeur'], errors='coerce')

# Les 9 valeurs avec des caractères non numérique deviennent alors des NaN dans la colonne 'Valeur' (44+9=53)
# On a alors 53 lignes avec des valeurs NaN dans la colonne 'Valeur'
print(df_cout_ali_saine_2017_clean.isna().sum())

print("#################################################################################################")
print(f"Type de la colonne 'Valeur' : {df_cout_ali_saine_2017_clean['Valeur'].dtype}")
print("#################################################################################################")

Code Domaine               0
Domaine                    0
Code zone (ISO3)           0
Zone                       0
Code Élément               0
Élément                    0
Code Produit               0
Produit                    0
Code année                 0
Année                      0
Édition                    0
Unité                      0
Valeur                    53
Symbole                    0
Description du Symbole     0
dtype: int64
#################################################################################################
Type de la colonne 'Valeur' : float64
#################################################################################################

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Nom des colonnes et suppression</h3>
</div>

In [43]:
nom_colonnes_df_cout_ali_saine_2017_clean = df_cout_ali_saine_2017_clean.columns

for colonne_df_cout_ali_saine in nom_colonnes_df_cout_ali_saine_2017_clean:
    print(colonne_df_cout_ali_saine)

display(df_cout_ali_saine_2017_clean)

Code Domaine
Domaine
Code zone (ISO3)
Zone
Code Élément
Élément
Code Produit
Produit
Code année
Année
Édition
Unité
Valeur
Symbole
Description du Symbole

,Code Domaine,Domaine,Code zone (ISO3),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Édition,Unité,Valeur,Symbole,Description du Symbole
0,CAHD,Coût et abordabilité d’une alimentation saine\...,ZAF,Afrique du Sud,6205,Valeur,70041,"Cost of a healthy diet (CoHD), LCU per person ...",2017,2017,Juillet 2025 (rapport SOFI),UML/personne/jour,19.96,E,Valeur estimée
1,CAHD,Coût et abordabilité d’une alimentation saine\...,ZAF,Afrique du Sud,6226,Valeur,70040,"Cost of a healthy diet (CoHD), PPP dollar per ...",2017,2017,Juillet 2025 (rapport SOFI),Int$ (PPP) per person per day,3.00,E,Valeur estimée
2,CAHD,Coût et abordabilité d’une alimentation saine\...,ZAF,Afrique du Sud,6121,Valeur,7005,"Prevalence of unaffordability (PUA), percent",2017,2017,Juillet 2025 (rapport SOFI),%,60.80,E,Valeur estimée
3,CAHD,Coût et abordabilité d’une alimentation saine\...,ZAF,Afrique du Sud,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,35.00,E,Valeur estimée
4,CAHD,Coût et abordabilité d’une alimentation saine\...,ALB,Albanie,6205,Valeur,70041,"Cost of a healthy diet (CoHD), LCU per person ...",2017,2017,Juillet 2025 (rapport SOFI),UML/personne/jour,160.41,E,Valeur estimée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,CAHD,Coût et abordabilité d’une alimentation saine\...,ZMB,Zambie,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,13.60,E,Valeur estimée
696,CAHD,Coût et abordabilité d’une alimentation saine\...,ZWE,Zimbabwe,6205,Valeur,70041,"Cost of a healthy diet (CoHD), LCU per person ...",2017,2017,Juillet 2025 (rapport SOFI),UML/personne/jour,1.68,E,Valeur estimée
697,CAHD,Coût et abordabilité d’une alimentation saine\...,ZWE,Zimbabwe,6226,Valeur,70040,"Cost of a healthy diet (CoHD), PPP dollar per ...",2017,2017,Juillet 2025 (rapport SOFI),Int$ (PPP) per person per day,3.54,E,Valeur estimée
698,CAHD,Coût et abordabilité d’une alimentation saine\...,ZWE,Zimbabwe,6121,Valeur,7005,"Prevalence of unaffordability (PUA), percent",2017,2017,Juillet 2025 (rapport SOFI),%,75.50,E,Valeur estimée
699,CAHD,Coût et abordabilité d’une alimentation saine\...,ZWE,Zimbabwe,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,11.20,E,Valeur estimée

In [44]:
#On ne garde que les colonnes 'Code zone (ISO3)', 'Zone', 'Unité', 'Valeur'
df_cout_ali_saine_2017_clean = df_cout_ali_saine_2017_clean[['Code zone (ISO3)', 'Zone', 'Produit', 'Unité', 'Valeur']]

#Renommage des colonnes
df_cout_ali_saine_2017_clean.columns = ['Code Pays', 'Zone', 'Produit', 'Unité', 'Valeur']

display(df_cout_ali_saine_2017_clean)

,Code Pays,Zone,Produit,Unité,Valeur
0,ZAF,Afrique du Sud,"Cost of a healthy diet (CoHD), LCU per person ...",UML/personne/jour,19.96
1,ZAF,Afrique du Sud,"Cost of a healthy diet (CoHD), PPP dollar per ...",Int$ (PPP) per person per day,3.00
2,ZAF,Afrique du Sud,"Prevalence of unaffordability (PUA), percent",%,60.80
3,ZAF,Afrique du Sud,Number of people unable to afford a healthy di...,millions de No,35.00
4,ALB,Albanie,"Cost of a healthy diet (CoHD), LCU per person ...",UML/personne/jour,160.41
...,...,...,...,...,...
695,ZMB,Zambie,Number of people unable to afford a healthy di...,millions de No,13.60
696,ZWE,Zimbabwe,"Cost of a healthy diet (CoHD), LCU per person ...",UML/personne/jour,1.68
697,ZWE,Zimbabwe,"Cost of a healthy diet (CoHD), PPP dollar per ...",Int$ (PPP) per person per day,3.54
698,ZWE,Zimbabwe,"Prevalence of unaffordability (PUA), percent",%,75.50
699,ZWE,Zimbabwe,Number of people unable to afford a healthy di...,millions de No,11.20

In [45]:
df_cout_ali_saine_2017_clean = df_cout_ali_saine_2017_clean[df_cout_ali_saine_2017_clean['Produit']
    .isin(["Number of people unable to afford a healthy diet (NUA), million"])]

display(df_cout_ali_saine_2017_clean)

,Code Pays,Zone,Produit,Unité,Valeur
3,ZAF,Afrique du Sud,Number of people unable to afford a healthy di...,millions de No,35.0
7,ALB,Albanie,Number of people unable to afford a healthy di...,millions de No,0.7
11,DZA,Algérie,Number of people unable to afford a healthy di...,millions de No,7.8
15,DEU,Allemagne,Number of people unable to afford a healthy di...,millions de No,2.3
19,AGO,Angola,Number of people unable to afford a healthy di...,millions de No,18.4
...,...,...,...,...,...
683,TUR,Türkiye,Number of people unable to afford a healthy di...,millions de No,9.7
687,URY,Uruguay,Number of people unable to afford a healthy di...,millions de No,1.0
691,VNM,Viet Nam,Number of people unable to afford a healthy di...,millions de No,11.5
695,ZMB,Zambie,Number of people unable to afford a healthy di...,millions de No,13.6
699,ZWE,Zimbabwe,Number of people unable to afford a healthy di...,millions de No,11.2

In [46]:
#Pivot - On bascule les lignes du format "Long" au format "Large"

df_cout_ali_saine_2017_clean_pivot = df_cout_ali_saine_2017_clean.pivot_table(    ### p=production, x=exportation, m=importation
    index=['Zone', 'Code Pays'],     # Une seule ligne par pays (Zone)
    columns=['Produit'],             # 'Number of people unable to afford a healthy diet (NUA), million' devient une nouvelle colonne
    values='Valeur',                 # On remplit avec les chiffres de la colonne Valeur
    aggfunc=lambda x: x.sum(min_count=1)  
).reset_index()

#Nettoyage final du nom des colonnes
df_cout_ali_saine_2017_clean_pivot.columns.name = None

df_cout_ali_saine_2017_clean_pivot = df_cout_ali_saine_2017_clean_pivot.drop(columns=['Zone'])

#Inspection nouvelles données
from mes_fonctions import inspector
inspector(df_cout_ali_saine_2017_clean_pivot)

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 145 ; Nb de colonnes: 2

----------------------
Types de données:
Code Pays                                                           object
Number of people unable to afford a healthy diet (NUA), million    float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Code Pays                                                          145
Number of people unable to afford a healthy diet (NUA), million     83
dtype: int64

----------------------
Valeurs manquantes:
Code Pays                                                          0
Number of people unable to afford a healthy diet (NUA), million    0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

    Code Pays  Number of people unable to afford a healthy diet (NUA), million
0         ZAF                                               35.0
1         ALB                                                0.7
2         DZA                                                7.8
3         DEU                                                2.3
4         AGO                                               18.4
..        ...                                                ...
140       EGY                                               54.6
141       ARE                                                0.3
142       ECU                                                3.9
143       USA                                               16.6
144       ETH                                               68.2

[145 rows x 2 columns]

##############################################################################

In [47]:
df_cout_ali_saine_2017_clean_pivot["Number of people unable to afford a healthy diet (NUA), million"] = (
    df_cout_ali_saine_2017_clean_pivot["Number of people unable to afford a healthy diet (NUA), million"] * 1_000_000
)

df_cout_ali_saine_2017_clean_pivot = df_cout_ali_saine_2017_clean_pivot.rename(
    columns={"Number of people unable to afford a healthy diet (NUA), million": "Number of people unable to afford a healthy diet (NUA)"})

display(df_cout_ali_saine_2017_clean_pivot)

    Code Pays  Number of people unable to afford a healthy diet (NUA)
0         ZAF                                         35000000.0
1         ALB                                           700000.0
2         DZA                                          7800000.0
3         DEU                                          2300000.0
4         AGO                                         18400000.0
..        ...                                                ...
140       EGY                                         54600000.0
141       ARE                                           300000.0
142       ECU                                          3900000.0
143       USA                                         16600000.0
144       ETH                                         68200000.0

[145 rows x 2 columns]

In [48]:
#Renommage des colonnes
df_cout_ali_saine_2017_clean_pivot.columns = ["Code Pays",
                                              "Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine"]

display(df_cout_ali_saine_2017_clean_pivot)

,Code Pays,Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine
0,ZAF,35000000.0
1,ALB,700000.0
2,DZA,7800000.0
3,DEU,2300000.0
4,AGO,18400000.0
...,...,...
140,EGY,54600000.0
141,ARE,300000.0
142,ECU,3900000.0
143,USA,16600000.0
144,ETH,68200000.0

In [49]:
# Compte le nombre total de lignes ayant au moins un NaN
# Avec la fonction pivot le nombre de lignes avec des NaN peut diminuer car plusieurs Nan peuvent être sur une même ligne avec le pivot effectué
nb_df_cout_ali_saine_2017_clean_pivot = df_cout_ali_saine_2017_clean_pivot.isna().any(axis=1).sum()

print(f"Nombre de lignes avec au moins un NaN : {nb_df_cout_ali_saine_2017_clean_pivot}")

df_cout_ali_saine_2017_clean_pivot[df_cout_ali_saine_2017_clean_pivot.isna().any(axis=1)]

Nombre de lignes avec au moins un NaN : 0

Empty DataFrame
Columns: [Code Pays, Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine]
Index: []

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Inspection fin</h3>
</div>

In [50]:
#Inspection nouvelles données
from mes_fonctions import inspector
inspector(df_cout_ali_saine_2017_clean_pivot)

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 145 ; Nb de colonnes: 2

----------------------
Types de données:
Code Pays                                                                         object
Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine    float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Code Pays                                                                        145
Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine     83
dtype: int64

----------------------
Valeurs manquantes:
Code Pays                                                                        0
Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine    0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Code Pays,Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine
0,ZAF,35000000.0
1,ALB,700000.0
2,DZA,7800000.0
3,DEU,2300000.0
4,AGO,18400000.0
...,...,...
140,EGY,54600000.0
141,ARE,300000.0
142,ECU,3900000.0
143,USA,16600000.0
144,ETH,68200000.0

##############################################################################

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2.5 - Nettoyage - 'Stabilité_politique_par_pays_2017' - df_stability_2017_clean</h2>
</div>

<div style="border: 1px solid RGB(150, 20, 30); padding: 20px;">
    <h3 style="margin: 0; color: RGB(0, 50, 230); line-height: 1.6;">
        Variable :<br>
        • Stabilité politique
    </h3>
</div>

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Inspection</h3>
</div>

In [51]:
# --- Nettoyage ---
df_stability_2017_clean = df_stability_2017.copy()
print("📊 --- ÉTAT INITIAL ---")

from mes_fonctions import inspector
inspector(df_stability_2017_clean)

📊 --- ÉTAT INITIAL ---
#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 221 ; Nb de colonnes: 5

----------------------
Types de données:
Country Name     object
Country Code     object
Series Name      object
Series Code      object
2017 [YR2017]    object
dtype: object

----------------------
Nombre de doublons: 2

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Country Name     218
Country Code     216
Series Name        1
Series Code        1
2017 [YR2017]    206
dtype: int64

----------------------
Valeurs manquantes:
Country Name     3
Country Code     5
Series Name      5
Series Code      5
2017 [YR2017]    5
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Country Name,Country Code,Series Name,Series Code,2017 [YR2017]
0,Afghanistan,AFG,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,-2.61393089999999
1,Albania,ALB,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,0.1638298
2,Algeria,DZA,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,-0.929504599999999
3,American Samoa,ASM,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,1.2555945
4,Andorra,AND,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,1.3250909
...,...,...,...,...,...
216,NaN,NaN,NaN,NaN,NaN
217,NaN,NaN,NaN,NaN,NaN
218,NaN,NaN,NaN,NaN,NaN
219,Data from database: Worldwide Governance Indic...,NaN,NaN,NaN,NaN
220,Last Updated: 03/18/2026,NaN,NaN,NaN,NaN

##############################################################################

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Nom des colonnes et suppression</h3>
</div>

In [52]:
nom_colonnes_df_stability_2017_clean = df_stability_2017_clean.columns

for colonne_df_stability in nom_colonnes_df_stability_2017_clean:
    print(colonne_df_stability)
display(df_stability_2017_clean)

Country Name
Country Code
Series Name
Series Code
2017 [YR2017]

,Country Name,Country Code,Series Name,Series Code,2017 [YR2017]
0,Afghanistan,AFG,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,-2.61393089999999
1,Albania,ALB,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,0.1638298
2,Algeria,DZA,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,-0.929504599999999
3,American Samoa,ASM,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,1.2555945
4,Andorra,AND,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,1.3250909
...,...,...,...,...,...
216,NaN,NaN,NaN,NaN,NaN
217,NaN,NaN,NaN,NaN,NaN
218,NaN,NaN,NaN,NaN,NaN
219,Data from database: Worldwide Governance Indic...,NaN,NaN,NaN,NaN
220,Last Updated: 03/18/2026,NaN,NaN,NaN,NaN

In [53]:
#On ne garde que les colonnes 'Country Name', 'Country Code', '2017 [YR2017]'
df_stability_2017_clean = df_stability_2017_clean[['Country Name', 'Country Code', '2017 [YR2017]']]
display(df_stability_2017_clean)

,Country Name,Country Code,2017 [YR2017]
0,Afghanistan,AFG,-2.61393089999999
1,Albania,ALB,0.1638298
2,Algeria,DZA,-0.929504599999999
3,American Samoa,ASM,1.2555945
4,Andorra,AND,1.3250909
...,...,...,...
216,NaN,NaN,NaN
217,NaN,NaN,NaN
218,NaN,NaN,NaN
219,Data from database: Worldwide Governance Indic...,NaN,NaN
220,Last Updated: 03/18/2026,NaN,NaN

In [54]:
#Renommage des colonnes
df_stability_2017_clean.columns = ['Zone', 'Code Pays', 'Stability Score']
display(df_stability_2017_clean)

,Zone,Code Pays,Stability Score
0,Afghanistan,AFG,-2.61393089999999
1,Albania,ALB,0.1638298
2,Algeria,DZA,-0.929504599999999
3,American Samoa,ASM,1.2555945
4,Andorra,AND,1.3250909
...,...,...,...
216,NaN,NaN,NaN
217,NaN,NaN,NaN
218,NaN,NaN,NaN
219,Data from database: Worldwide Governance Indic...,NaN,NaN
220,Last Updated: 03/18/2026,NaN,NaN

In [55]:
# Enlève les lignes qui comporte des NAN - il s'agit de lignes suplémentaires qui ne comporte pas de pays
df_stability_2017_clean = df_stability_2017_clean.dropna()

df_stability_2017_clean = df_stability_2017_clean.drop(columns=['Zone'])

display(df_stability_2017_clean)

    Code Pays     Stability Score
0         AFG   -2.61393089999999
1         ALB           0.1638298
2         DZA  -0.929504599999999
3         ASM           1.2555945
4         AND           1.3250909
..        ...                 ...
211       VIR           0.8126545
212       PSE          -1.3682541
213       YEM          -2.7305026
214       ZMB  -0.211101999999999
215       ZWE          -0.8348774

[216 rows x 2 columns]

In [56]:
# Type des données
# Conversion de la colonne 'Stability Score' en float
df_stability_2017_clean['Stability Score'] = pd.to_numeric(
    df_stability_2017_clean['Stability Score'], 
    errors='coerce'
)

print(df_stability_2017_clean['Stability Score'].dtypes)

float64

In [57]:
# On arrondi à 2 chiffres après la virgule
df_stability_2017_clean['Stability Score'] = df_stability_2017_clean['Stability Score'].round(2)

display(df_stability_2017_clean)

    Code Pays  Stability Score
0         AFG            -2.61
1         ALB             0.16
2         DZA            -0.93
3         ASM             1.26
4         AND             1.33
..        ...              ...
211       VIR             0.81
212       PSE            -1.37
213       YEM            -2.73
214       ZMB            -0.21
215       ZWE            -0.83

[216 rows x 2 columns]

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Inspection fin</h3>
</div>

In [58]:
from mes_fonctions import inspector
inspector(df_stability_2017_clean)

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 216 ; Nb de colonnes: 2

----------------------
Types de données:
Code Pays           object
Stability Score    float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Code Pays          216
Stability Score    157
dtype: int64

----------------------
Valeurs manquantes:
Code Pays          0
Stability Score    4
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

    Code Pays  Stability Score
0         AFG            -2.61
1         ALB             0.16
2         DZA            -0.93
3         ASM             1.26
4         AND             1.33
..        ...              ...
211       VIR             0.81
212       PSE            -1.37
213       YEM            -2.73
214       ZMB            -0.21
215       ZWE            -0.83

[216 rows x 2 columns]

##############################################################################

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">ISO3</h2>
</div>

In [59]:
# Application de la fonction pour créer la clé commune 'Code Pays'
df_dispoali_2017_clean_pivot['Code Pays'] = df_dispoali_2017_clean_pivot['Zone'].apply(get_iso3_exact)
df_pop_2017_clean['Code Pays'] = df_pop_2017_clean['Zone'].apply(get_iso3_exact)
df_pib_2017_clean['Code Pays'] = df_pib_2017_clean['Zone'].apply(get_iso3_exact)

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">df_dispoali_2017_clean_pivot</h3>
</div>

In [60]:
# Compte le nombre exact de lignes avec NaN dans cette colonne
print(df_dispoali_2017_clean_pivot['Code Pays'].isna().sum())

print("############################################")

# Extrait la liste unique des zones où le Code Pays est manquant
zones_manquantes = df_dispoali_2017_clean_pivot[df_dispoali_2017_clean_pivot['Code Pays'].isna()]['Zone'].unique()
print("\n".join(zones_manquantes))

114
############################################
Afrique du Sud
Albanie
Algérie
Allemagne
Antigua-et-Barbuda
Arabie saoudite
Argentine
Arménie
Australie
Autriche
Azerbaïdjan
Barbade
Belgique
Bolivie
Bosnie-Herzégovine
Brésil
Bulgarie
Bélarus
Bénin
Cambodge
Cameroun
Chili
Chine - RAS de Hong-Kong
Chine - RAS de Macao
Chine, Taiwan Province de
Chine, continentale
Chypre
Colombie
Croatie
Danemark
Dominique
Espagne
Estonie
Fidji
Finlande
Fédération de Russie
Gambie
Grenade
Grèce
Guinée
Guinée-Bissau
Géorgie
Haïti
Hongrie
Inde
Indonésie
Irlande
Islande
Israël
Italie
Jamaïque
Japon
Jordanie
Kirghizistan
Koweït
Lettonie
Liban
Libéria
Lituanie
Macédoine du Nord
Malaisie
Malte
Maroc
Maurice
Mauritanie
Mexique
Mongolie
Monténégro
Namibie
Nigéria
Norvège
Nouvelle-Calédonie
Nouvelle-Zélande
Népal
Ouganda
Pays-Bas
Pologne
Polynésie française
Pérou
Roumanie
Royaume-Uni de Grande-Bretagne et d'Irlande du Nord
République centrafricaine
République de Corée
République de Moldova
République dominicaine
République populaire démocratique de Corée
République-Unie de Tanzanie
Saint-Kitts-et-Nevis
Saint-Vincent-et-les Grenadines
Sainte-Lucie
Sao Tomé-et-Principe
Serbie
Slovaquie
Slovénie
Soudan
Suisse
Suède
Sénégal
Tadjikistan
Tchad
Tchéquie
Thaïlande
Trinité-et-Tobago
Tunisie
Turkménistan
Turquie
Yémen
Zambie
Égypte
Émirats arabes unis
Équateur
États-Unis d'Amérique
Éthiopie
Îles Salomon

In [61]:
corrections_iso3_dispo = {
    'Afrique du Sud': 'ZAF',
    'Albanie': 'ALB',
    'Algérie': 'DZA',
    'Allemagne': 'DEU',
    'Antigua-et-Barbuda': 'ATG',
    'Arabie saoudite': 'SAU',
    'Argentine': 'ARG',
    'Arménie': 'ARM',
    'Australie': 'AUS',
    'Autriche': 'AUT',
    'Azerbaïdjan': 'AZE',
    'Barbade': 'BRB',
    'Belgique': 'BEL',
    'Bolivie': 'BOL',
    'Bosnie-Herzégovine': 'BIH',
    'Brésil': 'BRA',
    'Bulgarie': 'BGR',
    'Bélarus': 'BLR',
    'Bénin': 'BEN',
    'Cambodge': 'KHM',
    'Cameroun': 'CMR',
    'Chili': 'CHL',
    'Chine - RAS de Hong-Kong': 'HKG',
    'Chine - RAS de Macao': 'MAC',
    'Chine, Taiwan Province de': 'TWN',
    'Chine, continentale': 'CHN',
    'Chypre': 'CYP',
    'Colombie': 'COL',
    'Croatie': 'HRV',
    'Danemark': 'DNK',
    'Dominique': 'DMA',
    'Espagne': 'ESP',
    'Estonie': 'EST',
    'Fidji': 'FJI',
    'Finlande': 'FIN',
    'Fédération de Russie': 'RUS',
    'Gambie': 'GMB',
    'Grenade': 'GRD',
    'Grèce': 'GRC',
    'Guinée': 'GIN',
    'Guinée-Bissau': 'GNB',
    'Géorgie': 'GEO',
    'Haïti': 'HTI',
    'Hongrie': 'HUN',
    'Inde': 'IND',
    'Indonésie': 'IDN',
    'Irlande': 'IRL',
    'Islande': 'ISL',
    'Israël': 'ISR',
    'Italie': 'ITA',
    'Jamaïque': 'JAM',
    'Japon': 'JPN',
    'Jordanie': 'JOR',
    'Kirghizistan': 'KGZ',
    'Koweït': 'KWT',
    'Lettonie': 'LVA',
    'Liban': 'LBN',
    'Libéria': 'LBR',
    'Lituanie': 'LTU',
    'Macédoine du Nord': 'MKD',
    'Malaisie': 'MYS',
    'Malte': 'MLT',
    'Maroc': 'MAR',
    'Maurice': 'MUS',
    'Mauritanie': 'MRT',
    'Mexique': 'MEX',
    'Mongolie': 'MNG',
    'Monténégro': 'MNE',
    'Namibie': 'NAM',
    'Nigéria': 'NGA',
    'Norvège': 'NOR',
    'Nouvelle-Calédonie': 'NCL',
    'Nouvelle-Zélande': 'NZL',
    'Népal': 'NPL',
    'Ouganda': 'UGA',
    'Ouzbékistan': 'UZB',
    'Pays-Bas': 'NLD',
    'Pologne': 'POL',
    'Polynésie française': 'PYF',
    'Pérou': 'PER',
    'Roumanie': 'ROU',
    "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord": 'GBR',
    'République centrafricaine': 'CAF',
    'République de Corée': 'KOR',
    'République de Moldova': 'MDA',
    'République dominicaine': 'DOM',
    'République démocratique populaire lao': 'LAO',
    'République populaire démocratique de Corée': 'PRK',
    'République-Unie de Tanzanie': 'TZA',
    'Saint-Kitts-et-Nevis': 'KNA',
    'Saint-Vincent-et-les Grenadines': 'VCT',
    'Sainte-Lucie': 'LCA',
    'Sao Tomé-et-Principe': 'STP',
    'Serbie': 'SRB',
    'Slovaquie': 'SVK',
    'Slovénie': 'SVN',
    'Soudan': 'SDN',
    'Suisse': 'CHE',
    'Suède': 'SWE',
    'Sénégal': 'SEN',
    'Tadjikistan': 'TJK',
    'Tchad': 'TCD',
    'Tchéquie': 'CZE',
    'Thaïlande': 'THA',
    'Trinité-et-Tobago': 'TTO',
    'Tunisie': 'TUN',
    'Turkménistan': 'TKM',
    'Turquie': 'TUR',
    'Yémen': 'YEM',
    'Zambie': 'ZMB',
    'Égypte': 'EGY',
    'Émirats arabes unis': 'ARE',
    'Équateur': 'ECU',
    "États-Unis d'Amérique": 'USA',
    'Éthiopie': 'ETH',
    'Îles Salomon': 'SLB'
}

In [62]:
# On remplace les NaN de 'Code Pays' en cherchant la correspondance de la 'Zone' dans le dictionnaire
df_dispoali_2017_clean_pivot['Code Pays'] = df_dispoali_2017_clean_pivot['Code Pays'].fillna(
    df_dispoali_2017_clean_pivot['Zone'].map(corrections_iso3_dispo)
)

In [63]:
# Vérification
nb_nan = df_dispoali_2017_clean_pivot['Code Pays'].isna().sum()
print(f"Nombre de lignes avec NaN restantes : {nb_nan}")

if nb_nan > 0:
    print("Certains pays n'ont pas encore de code ISO3 :")
    print(df_dispoali_2017_clean_pivot[df_dispoali_2017_clean_pivot['Code Pays'].isna()]['Zone'].unique())

Nombre de lignes avec NaN restantes : 0

In [64]:
display(df_dispoali_2017_clean_pivot)

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,AFG
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF
2,Albanie,16.36,47.0,0.0,38.0,13.0,ALB
3,Algérie,6.38,277.0,0.0,2.0,275.0,DZA
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU
...,...,...,...,...,...,...,...
167,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE
168,Équateur,19.31,341.0,0.0,0.0,340.0,ECU
169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA
170,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH
171,Îles Salomon,4.45,3.0,0.0,6.0,0.0,SLB

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">df_pop_2017_clean</h3>
</div>

In [65]:
# Compte le nombre exact de lignes avec NaN dans cette colonne
print(df_pop_2017_clean['Code Pays'].isna().sum())

print("############################################")

# Extrait la liste unique des zones où le Code Pays est manquant
zones_manquantes = df_pop_2017_clean[df_pop_2017_clean['Code Pays'].isna()]['Zone'].unique()
print("\n".join(zones_manquantes))

162
############################################
Afrique du Sud
Albanie
Algérie
Allemagne
Andorre
Antigua-et-Barbuda
Antilles néerlandaises
Arabie saoudite
Argentine
Arménie
Australie
Autriche
Azerbaïdjan
Bahreïn
Barbade
Bélarus
Belgique
Bénin
Bermudes
Bhoutan
Bolivie
Bonaire, Saint-Eustache et Saba
Bosnie-Herzégovine
Brésil
Brunéi Darussalam
Bulgarie
Cambodge
Cameroun
Chili
Chine - RAS de Hong-Kong
Chine - RAS de Macao
Chine, continentale
Chine, Taiwan Province de
Chypre
Colombie
Comores
Croatie
Danemark
Dominique
Égypte
Émirats arabes unis
Équateur
Érythrée
Espagne
Estonie
États-Unis d'Amérique
Éthiopie
Fédération de Russie
Fidji
Finlande
Gambie
Géorgie
Grèce
Grenade
Groenland
Guinée
Guinée équatoriale
Guinée-Bissau
Guyane française
Haïti
Hongrie
Île de Man
Îles Anglo-Normandes
Îles Caïmanes
Îles Cook
Îles Falkland
Îles Féroé
Îles Mariannes du Nord
Îles Marshall
Îles Salomon
Îles Turques-et-Caïques
Îles Vierges américaines
Îles Vierges britanniques
Îles Wallis-et-Futuna
Inde
Indonésie
Irlande
Islande
Israël
Italie
Jamaïque
Japon
Jordanie
Kirghizistan
Koweït
Lettonie
Liban
Libéria
Libye
Lituanie
Macédoine du Nord
Malaisie
Malte
Maroc
Maurice
Mauritanie
Mexique
Micronésie
Mongolie
Monténégro
Namibie
Népal
Nigéria
Nioué
Norvège
Nouvelle-Calédonie
Nouvelle-Zélande
Ouganda
Ouzbékistan
Palaos
Palestine
Papouasie-Nouvelle-Guinée
Pays-Bas
Pérou
Pologne
Polynésie française
Porto Rico
République arabe syrienne
République centrafricaine
République de Corée
République de Moldova
République démocratique du Congo
République démocratique populaire lao
République dominicaine
République populaire démocratique de Corée
République-Unie de Tanzanie
Roumanie
Royaume-Uni de Grande-Bretagne et d'Irlande du Nord
Sahara occidental
Saint-Barthélemy
Sainte-Hélène, Ascension et Tristan da Cunha
Sainte-Lucie
Saint-Kitts-et-Nevis
Saint-Marin
Saint-Martin
Saint-Pierre-et-Miquelon
Saint-Siège
Saint-Vincent-et-les Grenadines
Samoa américaines
Sao Tomé-et-Principe
Sénégal
Serbie
Singapour
Sint Maarten
Slovaquie
Slovénie
Somalie
Soudan
Soudan du Sud
Suède
Suisse
Tadjikistan
Tchad
Tchéquie
Thaïlande
Tokélaou
Trinité-et-Tobago
Tunisie
Turkménistan
Turquie
Yémen
Zambie

In [66]:
# 1. Définition du dictionnaire complet de correspondance ISO3
corrections_iso3_pop = {
    'Afrique du Sud': 'ZAF',
    'Albanie': 'ALB',
    'Algérie': 'DZA',
    'Allemagne': 'DEU',
    'Andorre': 'AND',
    'Antigua-et-Barbuda': 'ATG',
    'Antilles néerlandaises': 'ANT',
    'Arabie saoudite': 'SAU',
    'Argentine': 'ARG',
    'Arménie': 'ARM',
    'Australie': 'AUS',
    'Autriche': 'AUT',
    'Azerbaïdjan': 'AZE',
    'Bahreïn': 'BHR',
    'Barbade': 'BRB',
    'Bélarus': 'BLR',
    'Belgique': 'BEL',
    'Bénin': 'BEN',
    'Bermudes': 'BMU',
    'Bhoutan': 'BTN',
    'Bolivie': 'BOL',
    'Bonaire, Saint-Eustache et Saba': 'BES',
    'Bosnie-Herzégovine': 'BIH',
    'Brésil': 'BRA',
    'Brunéi Darussalam': 'BRN',
    'Bulgarie': 'BGR',
    'Cambodge': 'KHM',
    'Cameroun': 'CMR',
    'Chili': 'CHL',
    'Chine - RAS de Hong-Kong': 'HKG',
    'Chine - RAS de Macao': 'MAC',
    'Chine, continentale': 'CHN',
    'Chine, Taiwan Province de': 'TWN',
    'Chypre': 'CYP',
    'Colombie': 'COL',
    'Comores': 'COM',
    'Croatie': 'HRV',
    'Danemark': 'DNK',
    'Dominique': 'DMA',
    'Égypte': 'EGY',
    'Émirats arabes unis': 'ARE',
    'Équateur': 'ECU',
    'Érythrée': 'ERI',
    'Espagne': 'ESP',
    'Estonie': 'EST',
    "États-Unis d'Amérique": 'USA',
    'Éthiopie': 'ETH',
    'Fédération de Russie': 'RUS',
    'Fidji': 'FJI',
    'Finlande': 'FIN',
    'Gambie': 'GMB',
    'Géorgie': 'GEO',
    'Grèce': 'GRC',
    'Grenade': 'GRD',
    'Groenland': 'GRL',
    'Guinée': 'GIN',
    'Guinée équatoriale': 'GNQ',
    'Guinée-Bissau': 'GNB',
    'Guyane française': 'GUF',
    'Haïti': 'HTI',
    'Hongrie': 'HUN',
    'Île de Man': 'IMN',
    'Îles Anglo-Normandes': 'CHI',
    'Îles Caïmanes': 'CYM',
    'Îles Cook': 'COK',
    'Îles Falkland': 'FLK',
    'Îles Féroé': 'FRO',
    'Îles Mariannes du Nord': 'MNP',
    'Îles Marshall': 'MHL',
    'Îles Salomon': 'SLB',
    'Îles Turques-et-Caïques': 'TCA',
    'Îles Vierges américaines': 'VIR',
    'Îles Vierges britanniques': 'VGB',
    'Îles Wallis-et-Futuna': 'WLF',
    'Inde': 'IND',
    'Indonésie': 'IDN',
    'Irlande': 'IRL',
    'Islande': 'ISL',
    'Israël': 'ISR',
    'Italie': 'ITA',
    'Jamaïque': 'JAM',
    'Japon': 'JPN',
    'Jordanie': 'JOR',
    'Kirghizistan': 'KGZ',
    'Koweït': 'KWT',
    'Lettonie': 'LVA',
    'Liban': 'LBN',
    'Libéria': 'LBR',
    'Libye': 'LBY',
    'Lituanie': 'LTU',
    'Macédoine du Nord': 'MKD',
    'Malaisie': 'MYS',
    'Malte': 'MLT',
    'Maroc': 'MAR',
    'Maurice': 'MUS',
    'Mauritanie': 'MRT',
    'Mexique': 'MEX',
    'Micronésie': 'FSM',
    'Mongolie': 'MNG',
    'Monténégro': 'MNE',
    'Namibie': 'NAM',
    'Népal': 'NPL',
    'Nigéria': 'NGA',
    'Nioué': 'NIU',
    'Norvège': 'NOR',
    'Nouvelle-Calédonie': 'NCL',
    'Nouvelle-Zélande': 'NZL',
    'Ouganda': 'UGA',
    'Ouzbékistan': 'UZB',
    'Palaos': 'PLW',
    'Palestine': 'PSE',
    'Papouasie-Nouvelle-Guinée': 'PNG',
    'Pays-Bas': 'NLD',
    'Pérou': 'PER',
    'Pologne': 'POL',
    'Polynésie française': 'PYF',
    'Porto Rico': 'PRI',
    'République arabe syrienne': 'SYR',
    'République centrafricaine': 'CAF',
    'République de Corée': 'KOR',
    'République de Moldova': 'MDA',
    'République démocratique du Congo': 'COD',
    'République démocratique populaire lao': 'LAO',
    'République dominicaine': 'DOM',
    'République populaire démocratique de Corée': 'PRK',
    'République-Unie de Tanzanie': 'TZA',
    'Roumanie': 'ROU',
    "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord": 'GBR',
    'Sahara occidental': 'ESH',
    'Saint-Barthélemy': 'BLM',
    'Sainte-Hélène, Ascension et Tristan da Cunha': 'SHN',
    'Sainte-Lucie': 'LCA',
    'Saint-Kitts-et-Nevis': 'KNA',
    'Saint-Marin': 'SMR',
    'Saint-Martin': 'MAF',
    'Saint-Pierre-et-Miquelon': 'SPM',
    'Saint-Siège': 'VAT',
    'Saint-Vincent-et-les Grenadines': 'VCT',
    'Samoa américaines': 'ASM',
    'Sao Tomé-et-Principe': 'STP',
    'Sénégal': 'SEN',
    'Serbie': 'SRB',
    'Singapour': 'SGP',
    'Sint Maarten': 'SXM',
    'Slovaquie': 'SVK',
    'Slovénie': 'SVN',
    'Somalie': 'SOM',
    'Soudan': 'SDN',
    'Soudan du Sud': 'SSD',
    'Suède': 'SWE',
    'Suisse': 'CHE',
    'Tadjikistan': 'TJK',
    'Tchad': 'TCD',
    'Tchéquie': 'CZE',
    'Thaïlande': 'THA',
    'Tokélaou': 'TKL',
    'Trinité-et-Tobago': 'TTO',
    'Tunisie': 'TUN',
    'Turkménistan': 'TKM',
    'Turquie': 'TUR',
    'Yémen': 'YEM',
    'Zambie': 'ZMB'
}

In [67]:
# On remplace les NaN de 'Code Pays' en cherchant la correspondance de la 'Zone' dans le dictionnaire
df_pop_2017_clean['Code Pays'] = df_pop_2017_clean['Code Pays'].fillna(
    df_pop_2017_clean['Zone'].map(corrections_iso3_pop)
)

In [68]:
# Vérification
nb_nan = df_pop_2017_clean['Code Pays'].isna().sum()
print(f"Nombre de lignes avec NaN restantes : {nb_nan}")

if nb_nan > 0:
    print("Certains pays n'ont pas encore de code ISO3 :")
    print(df_pop_2017_clean[df_pop_2017_clean['Code Pays'].isna()]['Zone'].unique())

Nombre de lignes avec NaN restantes : 0

In [69]:
df_pop_2017_clean = df_pop_2017_clean.drop(columns=['Zone'])
display(df_pop_2017_clean)

      Population Code Pays
17    36296113.0       AFG
36    57009756.0       ZAF
55     2884169.0       ALB
74    41389189.0       DZA
93    82658409.0       DEU
...          ...       ...
4333  29402484.0       VEN
4352  94600648.0       VNM
4371  27834819.0       YEM
4390  16853599.0       ZMB
4409  14236595.0       ZWE

[236 rows x 2 columns]

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">df_pib_2017_clean</h3>
</div>

In [70]:
# Compte le nombre exact de lignes avec NaN dans cette colonne
print(df_pib_2017_clean['Code Pays'].isna().sum())

print("############################################")

# Extrait la liste unique des zones où le Code Pays est manquant
zones_manquantes = df_pib_2017_clean[df_pib_2017_clean['Code Pays'].isna()]['Zone'].unique()
print("\n".join(zones_manquantes))

141
############################################
Afrique du Sud
Albanie
Algérie
Allemagne
Andorre
Antigua-et-Barbuda
Arabie saoudite
Argentine
Arménie
Australie
Autriche
Azerbaïdjan
Bahreïn
Barbade
Bélarus
Belgique
Bénin
Bermudes
Bhoutan
Bolivie
Bosnie-Herzégovine
Brésil
Brunéi Darussalam
Bulgarie
Cambodge
Cameroun
Chili
Chine - RAS de Hong-Kong
Chine - RAS de Macao
Chine, continentale
Chypre
Colombie
Comores
Croatie
Danemark
Dominique
Égypte
Émirats arabes unis
Équateur
Érythrée
Espagne
Estonie
États-Unis d'Amérique
Éthiopie
Fédération de Russie
Fidji
Finlande
Gambie
Géorgie
Grèce
Grenade
Groenland
Guinée
Guinée équatoriale
Guinée-Bissau
Haïti
Hongrie
Îles Caïmanes
Îles Cook
Îles Marshall
Îles Salomon
Îles Turques-et-Caïques
Îles Vierges britanniques
Inde
Indonésie
Irlande
Islande
Israël
Italie
Jamaïque
Japon
Jordanie
Kirghizistan
Koweït
Lettonie
Liban
Libéria
Libye
Lituanie
Macédoine du Nord
Malaisie
Malte
Maroc
Maurice
Mauritanie
Mexique
Micronésie
Mongolie
Monténégro
Namibie
Népal
Nigéria
Norvège
Nouvelle-Calédonie
Nouvelle-Zélande
Ouganda
Ouzbékistan
Palaos
Palestine
Papouasie-Nouvelle-Guinée
Pays-Bas
Pérou
Pologne
Polynésie française
Porto Rico
République arabe syrienne
République centrafricaine
République de Corée
République de Moldova
République démocratique du Congo
République démocratique populaire lao
République dominicaine
République populaire démocratique de Corée
République-Unie de Tanzanie
Roumanie
Royaume-Uni de Grande-Bretagne et d'Irlande du Nord
Sainte-Lucie
Saint-Kitts-et-Nevis
Saint-Marin
Saint-Vincent-et-les Grenadines
Sao Tomé-et-Principe
Sénégal
Serbie
Singapour
Sint Maarten
Slovaquie
Slovénie
Somalie
Soudan
Soudan du Sud
Suède
Suisse
Tadjikistan
Tchad
Tchéquie
Thaïlande
Trinité-et-Tobago
Tunisie
Turkménistan
Yémen
Zambie

In [71]:
corrections_iso3_pib = {
    "Afrique du Sud": "ZAF",
    "Albanie": "ALB",
    "Algérie": "DZA",
    "Allemagne": "DEU",
    "Andorre": "AND",
    "Antigua-et-Barbuda": "ATG",
    "Arabie saoudite": "SAU",
    "Argentine": "ARG",
    "Arménie": "ARM",
    "Australie": "AUS",
    "Autriche": "AUT",
    "Azerbaïdjan": "AZE",
    "Bahreïn": "BHR",
    "Barbade": "BRB",
    "Bélarus": "BLR",
    "Belgique": "BEL",
    "Bénin": "BEN",
    "Bermudes": "BMU",
    "Bhoutan": "BTN",
    "Bolivie": "BOL",
    "Bosnie-Herzégovine": "BIH",
    "Brésil": "BRA",
    "Brunéi Darussalam": "BRN",
    "Bulgarie": "BGR",
    "Cambodge": "KHM",
    "Cameroun": "CMR",
    "Chili": "CHL",
    "Chine - RAS de Hong-Kong": "HKG",
    "Chine - RAS de Macao": "MAC",
    "Chine, continentale": "CHN",
    "Chypre": "CYP",
    "Colombie": "COL",
    "Comores": "COM",
    "Croatie": "HRV",
    "Danemark": "DNK",
    "Dominique": "DMA",
    "Égypte": "EGY",
    "Émirats arabes unis": "ARE",
    "Équateur": "ECU",
    "Érythrée": "ERI",
    "Espagne": "ESP",
    "Estonie": "EST",
    "États-Unis d'Amérique": "USA",
    "Éthiopie": "ETH",
    "Fédération de Russie": "RUS",
    "Fidji": "FJI",
    "Finlande": "FIN",
    "Gambie": "GMB",
    "Géorgie": "GEO",
    "Grèce": "GRC",
    "Grenade": "GRD",
    "Groenland": "GRL",
    "Guinée": "GIN",
    "Guinée équatoriale": "GNQ",
    "Guinée-Bissau": "GNB",
    "Haïti": "HTI",
    "Hongrie": "HUN",
    "Îles Caïmanes": "CYM",
    "Îles Cook": "COK",
    "Îles Marshall": "MHL",
    "Îles Salomon": "SLB",
    "Îles Turques-et-Caïques": "TCA",
    "Îles Vierges britanniques": "VGB",
    "Inde": "IND",
    "Indonésie": "IDN",
    "Irlande": "IRL",
    "Islande": "ISL",
    "Israël": "ISR",
    "Italie": "ITA",
    "Jamaïque": "JAM",
    "Japon": "JPN",
    "Jordanie": "JOR",
    "Kirghizistan": "KGZ",
    "Koweït": "KWT",
    "Lettonie": "LVA",
    "Liban": "LBN",
    "Libéria": "LBR",
    "Libye": "LBY",
    "Lituanie": "LTU",
    "Macédoine du Nord": "MKD",
    "Malaisie": "MYS",
    "Malte": "MLT",
    "Maroc": "MAR",
    "Maurice": "MUS",
    "Mauritanie": "MRT",
    "Mexique": "MEX",
    "Micronésie": "FSM",
    "Mongolie": "MNG",
    "Monténégro": "MNE",
    "Namibie": "NAM",
    "Népal": "NPL",
    "Nigéria": "NGA",
    "Norvège": "NOR",
    "Nouvelle-Calédonie": "NCL",
    "Nouvelle-Zélande": "NZL",
    "Ouganda": "UGA",
    "Ouzbékistan": "UZB",
    "Palaos": "PLW",
    "Palestine": "PSE",
    "Papouasie-Nouvelle-Guinée": "PNG",
    "Pays-Bas": "NLD",
    "Pérou": "PER",
    "Pologne": "POL",
    "Polynésie française": "PYF",
    "Porto Rico": "PRI",
    "République arabe syrienne": "SYR",
    "République centrafricaine": "CAF",
    "République de Corée": "KOR",
    "République de Moldova": "MDA",
    "République démocratique du Congo": "COD",
    "République démocratique populaire lao": "LAO",
    "République dominicaine": "DOM",
    "République populaire démocratique de Corée": "PRK",
    "République-Unie de Tanzanie": "TZA",
    "Roumanie": "ROU",
    "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord": "GBR",
    "Sainte-Lucie": "LCA",
    "Saint-Kitts-et-Nevis": "KNA",
    "Saint-Marin": "SMR",
    "Saint-Vincent-et-les Grenadines": "VCT",
    "Sao Tomé-et-Principe": "STP",
    "Sénégal": "SEN",
    "Serbie": "SRB",
    "Singapour": "SGP",
    "Sint Maarten": "SXM",
    "Slovaquie": "SVK",
    "Slovénie": "SVN",
    "Somalie": "SOM",
    "Soudan": "SDN",
    "Soudan du Sud": "SSD",
    "Suède": "SWE",
    "Suisse": "CHE",
    "Tadjikistan": "TJK",
    "Tchad": "TCD",
    "Tchéquie": "CZE",
    "Thaïlande": "THA",
    "Trinité-et-Tobago": "TTO",
    "Tunisie": "TUN",
    "Turkménistan": "TKM",
    "Yémen": "YEM",
    "Zambie": "ZMB"
}

In [72]:
# On remplace les NaN de 'Code Pays' en cherchant la correspondance de la 'Zone' dans le dictionnaire
df_pib_2017_clean['Code Pays'] = df_pib_2017_clean['Code Pays'].fillna(
    df_pib_2017_clean['Zone'].map(corrections_iso3_pib)
)

In [73]:
# Vérification
nb_nan = df_pib_2017_clean['Code Pays'].isna().sum()
print(f"Nombre de lignes avec NaN restantes : {nb_nan}")

if nb_nan > 0:
    print("Certains pays n'ont pas encore de code ISO3 :")
    print(df_pib_2017_clean[df_pib_2017_clean['Code Pays'].isna()]['Zone'].unique())

Nombre de lignes avec NaN restantes : 0

In [74]:
df_pib_2017_clean = df_pib_2017_clean.drop(columns=['Zone'])
display(df_pib_2017_clean)

     PIB (en millions d'USD) Code Pays
0               1.903430e+04       AFG
1               3.811367e+05       ZAF
2               1.301973e+04       ALB
3               1.700970e+05       DZA
4               3.763092e+06       DEU
..                       ...       ...
205             2.470511e+05       VEN
206             2.813536e+05       VNM
207             1.839165e+04       YEM
208             2.590071e+04       ZMB
209             2.204065e+04       ZWE

[210 rows x 2 columns]

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Join</h2>
</div>

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Première fusion : df_dispoali_2017_clean_pivot + df_pop_2017_clean</h3>
</div>

In [75]:
print(df_dispoali_2017_clean_pivot.shape)

#Première fusion : #df_dispoali_2017_clean_pivot + df_pop_2017_clean
df_final = pd.merge(df_dispoali_2017_clean_pivot, df_pop_2017_clean, on="Code Pays", how="inner")

print(df_final.shape)
#inspector(df_final)
display(df_final)

(170, 7)
(170, 8)

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,AFG,36296113.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF,57009756.0
2,Albanie,16.36,47.0,0.0,38.0,13.0,ALB,2884169.0
3,Algérie,6.38,277.0,0.0,2.0,275.0,DZA,41389189.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU,82658409.0
...,...,...,...,...,...,...,...,...
165,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE,9487203.0
166,Équateur,19.31,341.0,0.0,0.0,340.0,ECU,16785361.0
167,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA,325084756.0
168,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH,106399924.0
169,Îles Salomon,4.45,3.0,0.0,6.0,0.0,SLB,636039.0

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Deuxième fusion : df_final + df_pib_2017_clean</h3>
</div>

In [76]:
# Quels codes pays de ma table principale sont ABSENTS de ma table de population ?
lignes_perdues = df_final[~df_final['Code Pays'].isin(df_pib_2017_clean['Code Pays'])]

display(lignes_perdues[['Zone', 'Code Pays']])

                         Zone Code Pays
33  Chine, Taiwan Province de       TWN

In [77]:
print(df_final.shape)

#Deuxième fusion : df_final + df_pib_2017_clean
df_final = pd.merge(df_final, df_pib_2017_clean, on="Code Pays", how="inner")

print(df_final.shape)
display(df_final)

(170, 8)
(169, 9)

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population,PIB (en millions d'USD)
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,AFG,36296113.0,1.903430e+04
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF,57009756.0,3.811367e+05
2,Albanie,16.36,47.0,0.0,38.0,13.0,ALB,2884169.0,1.301973e+04
3,Algérie,6.38,277.0,0.0,2.0,275.0,DZA,41389189.0,1.700970e+05
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU,82658409.0,3.763092e+06
...,...,...,...,...,...,...,...,...,...
164,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE,9487203.0,3.905168e+05
165,Équateur,19.31,341.0,0.0,0.0,340.0,ECU,16785361.0,1.044675e+05
166,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA,325084756.0,1.961210e+07
167,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH,106399924.0,7.679469e+04
168,Îles Salomon,4.45,3.0,0.0,6.0,0.0,SLB,636039.0,1.469790e+03

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Troisième fusion : df_final + df_cout_ali_saine_2017_clean_pivot</h3>
</div>

In [78]:
# Quels codes pays de ma table principale sont ABSENTS de ma table de population ?
lignes_perdues = df_final[~df_final['Code Pays'].isin(df_cout_ali_saine_2017_clean_pivot['Code Pays'])]

display(lignes_perdues[['Zone', 'Code Pays']])

                                           Zone Code Pays
0                                   Afghanistan       AFG
6                            Antigua-et-Barbuda       ATG
7                               Arabie saoudite       SAU
13                                      Bahamas       BHS
15                                      Barbade       BRB
27                                     Cambodge       KHM
31                     Chine - RAS de Hong-Kong       HKG
32                         Chine - RAS de Macao       MAC
39                                         Cuba       CUB
43                                    Dominique       DMA
44                                  El Salvador       SLV
55                                      Grenade       GRD
61                                      Géorgie       GEO
70                                      Islande       ISL
79                                     Kiribati       KIR
80                                       Koweït       KWT
86                                   Luxembourg       LUX
91                                     Maldives       MDV
93                                        Malte       MLT
107                          Nouvelle-Calédonie       NCL
110                                        Oman       OMN
118                         Polynésie française       PYF
128  République populaire démocratique de Corée       PRK
130                        Saint-Kitts-et-Nevis       KNA
131             Saint-Vincent-et-les Grenadines       VCT
132                                Sainte-Lucie       LCA
133                                       Samoa       WSM
149                                 Timor-Leste       TLS
153                                Turkménistan       TKM
155                                     Ukraine       UKR
157                                     Vanuatu       VUT
158                                   Venezuela       VEN
160                                       Yémen       YEM
168                                Îles Salomon       SLB

In [79]:
print(df_final.shape)

#Troisième fusion : df_final + df_cout_ali_saine_2017_clean_pivot
df_final = pd.merge(df_final, df_cout_ali_saine_2017_clean_pivot, on='Code Pays', how="inner")

print(df_final.shape)
display(df_final)

(169, 9)
(135, 10)

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population,PIB (en millions d'USD),Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine
0,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF,57009756.0,3.811367e+05,35000000.0
1,Albanie,16.36,47.0,0.0,38.0,13.0,ALB,2884169.0,1.301973e+04,700000.0
2,Algérie,6.38,277.0,0.0,2.0,275.0,DZA,41389189.0,1.700970e+05,7800000.0
3,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU,82658409.0,3.763092e+06,2300000.0
4,Angola,10.56,319.0,0.0,277.0,42.0,AGO,29816766.0,1.221239e+05,18400000.0
...,...,...,...,...,...,...,...,...,...,...
130,Égypte,12.96,1250.0,1.0,110.0,1118.0,EGY,96442591.0,2.055894e+05,54600000.0
131,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE,9487203.0,3.905168e+05,300000.0
132,Équateur,19.31,341.0,0.0,0.0,340.0,ECU,16785361.0,1.044675e+05,3900000.0
133,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA,325084756.0,1.961210e+07,16600000.0
134,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH,106399924.0,7.679469e+04,68200000.0

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Quatrième fusion : df_final + df_stability_2017_clean</h3>
</div>

In [80]:
print(df_final.shape)

#Troisième fusion : df_final + df_stability_2017_clean
df_final = pd.merge(df_final, df_stability_2017_clean, on='Code Pays', how="inner")

print(df_final.shape)
display(df_final)

(135, 10)
(135, 11)

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population,PIB (en millions d'USD),Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine,Stability Score
0,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF,57009756.0,3.811367e+05,35000000.0,-0.38
1,Albanie,16.36,47.0,0.0,38.0,13.0,ALB,2884169.0,1.301973e+04,700000.0,0.16
2,Algérie,6.38,277.0,0.0,2.0,275.0,DZA,41389189.0,1.700970e+05,7800000.0,-0.93
3,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU,82658409.0,3.763092e+06,2300000.0,0.70
4,Angola,10.56,319.0,0.0,277.0,42.0,AGO,29816766.0,1.221239e+05,18400000.0,-0.54
...,...,...,...,...,...,...,...,...,...,...,...
130,Égypte,12.96,1250.0,1.0,110.0,1118.0,EGY,96442591.0,2.055894e+05,54600000.0,-1.47
131,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE,9487203.0,3.905168e+05,300000.0,0.72
132,Équateur,19.31,341.0,0.0,0.0,340.0,ECU,16785361.0,1.044675e+05,3900000.0,-0.13
133,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA,325084756.0,1.961210e+07,16600000.0,0.11
134,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH,106399924.0,7.679469e+04,68200000.0,-1.52

In [81]:
inspector(df_final)

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 135 ; Nb de colonnes: 11

----------------------
Types de données:
Zone                                                                              object
Disponibilité alimentaire en quantité (kg/personne/an)                           float64
Disponibilité intérieure (en milliers de tonnes)                                 float64
Exportations - Quantité (en milliers de tonnes)                                  float64
Importations - Quantité (en milliers de tonnes)                                  float64
Production (en milliers de tonnes)                                               float64
Code Pays                                                                         object
Population                                                                       float64
PIB (en millions d'USD)                                                          float64
Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine    float64
Stability Score                                                                  float64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Zone                                                                             135
Disponibilité alimentaire en quantité (kg/personne/an)                           133
Disponibilité intérieure (en milliers de tonnes)                                 118
Exportations - Quantité (en milliers de tonnes)                                   47
Importations - Quantité (en milliers de tonnes)                                   76
Production (en milliers de tonnes)                                               113
Code Pays                                                                        135
Population                                                                       135
PIB (en millions d'USD)                                                          135
Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine     80
Stability Score                                                                  108
dtype: int64

----------------------
Valeurs manquantes:
Zone                                                                             0
Disponibilité alimentaire en quantité (kg/personne/an)                           0
Disponibilité intérieure (en milliers de tonnes)                                 0
Exportations - Quantité (en milliers de tonnes)                                  0
Importations - Quantité (en milliers de tonnes)                                  0
Production (en milliers de tonnes)                                               0
Code Pays                                                                        0
Population                                                                       0
PIB (en millions d'USD)                                                          0
Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine    0
Stability Score                                                                  0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population,PIB (en millions d'USD),Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine,Stability Score
0,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF,57009756.0,3.811367e+05,35000000.0,-0.38
1,Albanie,16.36,47.0,0.0,38.0,13.0,ALB,2884169.0,1.301973e+04,700000.0,0.16
2,Algérie,6.38,277.0,0.0,2.0,275.0,DZA,41389189.0,1.700970e+05,7800000.0,-0.93
3,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU,82658409.0,3.763092e+06,2300000.0,0.70
4,Angola,10.56,319.0,0.0,277.0,42.0,AGO,29816766.0,1.221239e+05,18400000.0,-0.54
...,...,...,...,...,...,...,...,...,...,...,...
130,Égypte,12.96,1250.0,1.0,110.0,1118.0,EGY,96442591.0,2.055894e+05,54600000.0,-1.47
131,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE,9487203.0,3.905168e+05,300000.0,0.72
132,Équateur,19.31,341.0,0.0,0.0,340.0,ECU,16785361.0,1.044675e+05,3900000.0,-0.13
133,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA,325084756.0,1.961210e+07,16600000.0,0.11
134,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH,106399924.0,7.679469e+04,68200000.0,-1.52

##############################################################################

In [82]:
# --- Export dataframe ---
df_final.to_csv("df_final.csv", index=False, sep=';', decimal=',', encoding='utf-8-sig')

print("✅ Fichier exporté")

✅ Fichier exporté

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Features</h2>
</div>

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Taux de dépendance à l’importation</h3>
</div>

In [83]:
consommation = (df_final['Production (en milliers de tonnes)'] + 
                df_final['Importations - Quantité (en milliers de tonnes)'] - 
                df_final['Exportations - Quantité (en milliers de tonnes)'])

df_final['Taux de dépendance à l’importation'] = df_final['Importations - Quantité (en milliers de tonnes)'] / consommation * 100

In [84]:
display(df_final)

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population,PIB (en millions d'USD),Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine,Stability Score,Taux de dépendance à l’importation
0,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF,57009756.0,3.811367e+05,35000000.0,-0.38,24.268178
1,Albanie,16.36,47.0,0.0,38.0,13.0,ALB,2884169.0,1.301973e+04,700000.0,0.16,74.509804
2,Algérie,6.38,277.0,0.0,2.0,275.0,DZA,41389189.0,1.700970e+05,7800000.0,-0.93,0.722022
3,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU,82658409.0,3.763092e+06,2300000.0,0.70,49.239766
4,Angola,10.56,319.0,0.0,277.0,42.0,AGO,29816766.0,1.221239e+05,18400000.0,-0.54,86.833856
...,...,...,...,...,...,...,...,...,...,...,...,...
130,Égypte,12.96,1250.0,1.0,110.0,1118.0,EGY,96442591.0,2.055894e+05,54600000.0,-1.47,8.964955
131,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE,9487203.0,3.905168e+05,300000.0,0.72,111.886305
132,Équateur,19.31,341.0,0.0,0.0,340.0,ECU,16785361.0,1.044675e+05,3900000.0,-0.13,0.000000
133,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA,325084756.0,1.961210e+07,16600000.0,0.11,0.670482
134,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH,106399924.0,7.679469e+04,68200000.0,-1.52,6.666667

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Production (en kg par habitant)</h3>
</div>

In [85]:
df_final['Production en kg par habitant'] = df_final['Production (en milliers de tonnes)'] / df_final.Population * 1_000_000

In [86]:
display(df_final)

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population,PIB (en millions d'USD),Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine,Stability Score,Taux de dépendance à l’importation,Production en kg par habitant
0,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF,57009756.0,3.811367e+05,35000000.0,-0.38,24.268178,29.240609
1,Albanie,16.36,47.0,0.0,38.0,13.0,ALB,2884169.0,1.301973e+04,700000.0,0.16,74.509804,4.507364
2,Algérie,6.38,277.0,0.0,2.0,275.0,DZA,41389189.0,1.700970e+05,7800000.0,-0.93,0.722022,6.644247
3,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU,82658409.0,3.763092e+06,2300000.0,0.70,49.239766,18.316346
4,Angola,10.56,319.0,0.0,277.0,42.0,AGO,29816766.0,1.221239e+05,18400000.0,-0.54,86.833856,1.408603
...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Égypte,12.96,1250.0,1.0,110.0,1118.0,EGY,96442591.0,2.055894e+05,54600000.0,-1.47,8.964955,11.592389
131,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE,9487203.0,3.905168e+05,300000.0,0.72,111.886305,5.059447
132,Équateur,19.31,341.0,0.0,0.0,340.0,ECU,16785361.0,1.044675e+05,3900000.0,-0.13,0.000000,20.255745
133,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA,325084756.0,1.961210e+07,16600000.0,0.11,0.670482,67.410113
134,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH,106399924.0,7.679469e+04,68200000.0,-1.52,6.666667,0.131579

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">PIB (en USD par habitant)</h3>
</div>

In [87]:
df_final['PIB par habitant (en USD)'] = df_final["PIB (en millions d'USD)"] / df_final.Population * 1_000_000

In [88]:
display(df_final)

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population,PIB (en millions d'USD),Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine,Stability Score,Taux de dépendance à l’importation,Production en kg par habitant,PIB par habitant (en USD)
0,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF,57009756.0,3.811367e+05,35000000.0,-0.38,24.268178,29.240609,6685.464789
1,Albanie,16.36,47.0,0.0,38.0,13.0,ALB,2884169.0,1.301973e+04,700000.0,0.16,74.509804,4.507364,4514.205415
2,Algérie,6.38,277.0,0.0,2.0,275.0,DZA,41389189.0,1.700970e+05,7800000.0,-0.93,0.722022,6.644247,4109.696067
3,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU,82658409.0,3.763092e+06,2300000.0,0.70,49.239766,18.316346,45525.825010
4,Angola,10.56,319.0,0.0,277.0,42.0,AGO,29816766.0,1.221239e+05,18400000.0,-0.54,86.833856,1.408603,4095.811665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Égypte,12.96,1250.0,1.0,110.0,1118.0,EGY,96442591.0,2.055894e+05,54600000.0,-1.47,8.964955,11.592389,2131.728063
131,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE,9487203.0,3.905168e+05,300000.0,0.72,111.886305,5.059447,41162.480029
132,Équateur,19.31,341.0,0.0,0.0,340.0,ECU,16785361.0,1.044675e+05,3900000.0,-0.13,0.000000,20.255745,6223.725883
133,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA,325084756.0,1.961210e+07,16600000.0,0.11,0.670482,67.410113,60329.196119
134,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH,106399924.0,7.679469e+04,68200000.0,-1.52,6.666667,0.131579,721.755084

<div style="border: 1px solid RGB(150, 20, 30);" >
<h3 style="margin: auto; padding: 20px; color: RGB(150, 20, 30); ">Taux de la population ayant les moyens de s'offrir une alimentation saine (en %)</h3>
</div>

In [89]:
df_final["Taux de la population ayant les moyens de s'offrir une alimentation saine (en %)"] = (100 -
    df_final["Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine"] 
    / df_final['Population'] * 100).round(0).astype('Int64')

In [90]:
display(df_final)

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population,PIB (en millions d'USD),Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine,Stability Score,Taux de dépendance à l’importation,Production en kg par habitant,PIB par habitant (en USD),Taux de la population ayant les moyens de s'offrir une alimentation saine (en %)
0,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF,57009756.0,3.811367e+05,35000000.0,-0.38,24.268178,29.240609,6685.464789,39
1,Albanie,16.36,47.0,0.0,38.0,13.0,ALB,2884169.0,1.301973e+04,700000.0,0.16,74.509804,4.507364,4514.205415,76
2,Algérie,6.38,277.0,0.0,2.0,275.0,DZA,41389189.0,1.700970e+05,7800000.0,-0.93,0.722022,6.644247,4109.696067,81
3,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU,82658409.0,3.763092e+06,2300000.0,0.70,49.239766,18.316346,45525.825010,97
4,Angola,10.56,319.0,0.0,277.0,42.0,AGO,29816766.0,1.221239e+05,18400000.0,-0.54,86.833856,1.408603,4095.811665,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Égypte,12.96,1250.0,1.0,110.0,1118.0,EGY,96442591.0,2.055894e+05,54600000.0,-1.47,8.964955,11.592389,2131.728063,43
131,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE,9487203.0,3.905168e+05,300000.0,0.72,111.886305,5.059447,41162.480029,97
132,Équateur,19.31,341.0,0.0,0.0,340.0,ECU,16785361.0,1.044675e+05,3900000.0,-0.13,0.000000,20.255745,6223.725883,77
133,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA,325084756.0,1.961210e+07,16600000.0,0.11,0.670482,67.410113,60329.196119,95
134,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH,106399924.0,7.679469e+04,68200000.0,-1.52,6.666667,0.131579,721.755084,36

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Retrait de la France (notre marché actuel) de la base de donnée</h2>
</div>

In [91]:
# Voir si la France se trouve dans notre data frame
print("Ligne à supprimer :")
display(df_final[df_final['Code Pays'] == 'FRA'])

Ligne à supprimer :

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population,PIB (en millions d'USD),Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine,Stability Score,Taux de dépendance à l’importation,Production en kg par habitant,PIB par habitant (en USD),Taux de la population ayant les moyens de s'offrir une alimentation saine (en %)
39,France,22.9,1573.0,501.0,506.0,1750.0,FRA,64842509.0,2.588868e+06,1200000.0,0.23,28.831909,26.988468,39925.480418,98

In [92]:
# On redéfinit le dataframe en excluant la France dont le Code ISO3 est 'FRA'
df_final = df_final[df_final['Code Pays'] != 'FRA']

In [93]:
# Vérification de la suppression
if 'FRA' not in df_final['Code Pays'].values:
    print("\n✅ La France a bien été retiré de la base de données.")

✅ La France a bien été retiré de la base de données.

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Inspection finale avant exportation</h2>
</div>

In [94]:
inspector(df_final)

#####     DEBUT DE L'INSPECTION     ############################################

----------------------
Structure du DataFrame:
Nb de lignes: 134 ; Nb de colonnes: 15

----------------------
Types de données:
Zone                                                                                 object
Disponibilité alimentaire en quantité (kg/personne/an)                              float64
Disponibilité intérieure (en milliers de tonnes)                                    float64
Exportations - Quantité (en milliers de tonnes)                                     float64
Importations - Quantité (en milliers de tonnes)                                     float64
Production (en milliers de tonnes)                                                  float64
Code Pays                                                                            object
Population                                                                          float64
PIB (en millions d'USD)                                                             float64
Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine       float64
Stability Score                                                                     float64
Taux de dépendance à l’importation                                                  float64
Production en kg par habitant                                                       float64
PIB par habitant (en USD)                                                           float64
Taux de la population ayant les moyens de s'offrir une alimentation saine (en %)      Int64
dtype: object

----------------------
Nombre de doublons: 0

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
Zone                                                                                134
Disponibilité alimentaire en quantité (kg/personne/an)                              132
Disponibilité intérieure (en milliers de tonnes)                                    117
Exportations - Quantité (en milliers de tonnes)                                      46
Importations - Quantité (en milliers de tonnes)                                      75
Production (en milliers de tonnes)                                                  112
Code Pays                                                                           134
Population                                                                          134
PIB (en millions d'USD)                                                             134
Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine        80
Stability Score                                                                     107
Taux de dépendance à l’importation                                                  114
Production en kg par habitant                                                       133
PIB par habitant (en USD)                                                           134
Taux de la population ayant les moyens de s'offrir une alimentation saine (en %)     72
dtype: int64

----------------------
Valeurs manquantes:
Zone                                                                                0
Disponibilité alimentaire en quantité (kg/personne/an)                              0
Disponibilité intérieure (en milliers de tonnes)                                    0
Exportations - Quantité (en milliers de tonnes)                                     0
Importations - Quantité (en milliers de tonnes)                                     0
Production (en milliers de tonnes)                                                  0
Code Pays                                                                           0
Population                                                                          0
PIB (en millions d'USD)                                                             0
Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine       0
Stability Score                                                                     0
Taux de dépendance à l’importation                                                  0
Production en kg par habitant                                                       0
PIB par habitant (en USD)                                                           0
Taux de la population ayant les moyens de s'offrir une alimentation saine (en %)    0
dtype: int64

#####     FIN DE L'INSPECTION     ############################################

#####      APERÇU DU TABLEAU      ############################################

,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Code Pays,Population,PIB (en millions d'USD),Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine,Stability Score,Taux de dépendance à l’importation,Production en kg par habitant,PIB par habitant (en USD),Taux de la population ayant les moyens de s'offrir une alimentation saine (en %)
0,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,ZAF,57009756.0,3.811367e+05,35000000.0,-0.38,24.268178,29.240609,6685.464789,39
1,Albanie,16.36,47.0,0.0,38.0,13.0,ALB,2884169.0,1.301973e+04,700000.0,0.16,74.509804,4.507364,4514.205415,76
2,Algérie,6.38,277.0,0.0,2.0,275.0,DZA,41389189.0,1.700970e+05,7800000.0,-0.93,0.722022,6.644247,4109.696067,81
3,Allemagne,19.47,1739.0,646.0,842.0,1514.0,DEU,82658409.0,3.763092e+06,2300000.0,0.70,49.239766,18.316346,45525.825010,97
4,Angola,10.56,319.0,0.0,277.0,42.0,AGO,29816766.0,1.221239e+05,18400000.0,-0.54,86.833856,1.408603,4095.811665,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Égypte,12.96,1250.0,1.0,110.0,1118.0,EGY,96442591.0,2.055894e+05,54600000.0,-1.47,8.964955,11.592389,2131.728063,43
131,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,ARE,9487203.0,3.905168e+05,300000.0,0.72,111.886305,5.059447,41162.480029,97
132,Équateur,19.31,341.0,0.0,0.0,340.0,ECU,16785361.0,1.044675e+05,3900000.0,-0.13,0.000000,20.255745,6223.725883,77
133,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,USA,325084756.0,1.961210e+07,16600000.0,0.11,0.670482,67.410113,60329.196119,95
134,Éthiopie,0.13,14.0,0.0,1.0,14.0,ETH,106399924.0,7.679469e+04,68200000.0,-1.52,6.666667,0.131579,721.755084,36

##############################################################################

In [95]:
    print("\n--------")
    print("RÉSUMÉ STATISTIQUES :")
    display(df_final.describe())

--------
RÉSUMÉ STATISTIQUES :

,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure (en milliers de tonnes),Exportations - Quantité (en milliers de tonnes),Importations - Quantité (en milliers de tonnes),Production (en milliers de tonnes),Population,PIB (en millions d'USD),Nombre de personnes n'ayant pas les moyens de s'offrir une alimentation saine,Stability Score,Taux de dépendance à l’importation,Production en kg par habitant,PIB par habitant (en USD),Taux de la population ayant les moyens de s'offrir une alimentation saine (en %)
count,134.000000,134.000000,134.000000,134.000000,134.000000,1.340000e+02,1.340000e+02,1.340000e+02,134.000000,134.000000,134.000000,134.000000,134.0
mean,17.909030,818.880597,122.104478,88.231343,868.634328,5.207813e+07,5.640011e+05,2.029403e+07,-0.155821,33.208750,18.024579,12826.288588,64.649254
std,13.802427,2440.388247,512.754485,182.356171,2778.086150,1.722355e+08,2.078595e+06,8.024554e+07,0.814843,40.367385,18.059468,17611.690646,26.432282
min,0.130000,2.000000,0.000000,0.000000,0.000000,2.070890e+05,3.785989e+02,1.000000e+05,-2.220000,0.000000,0.000000,450.900697,3.0
25%,5.892500,47.000000,0.000000,2.250000,26.500000,4.622526e+06,1.344016e+04,7.000000e+05,-0.700000,1.966515,2.565515,1861.243099,40.5
50%,16.250000,131.000000,1.000000,17.500000,102.500000,1.107878e+07,5.787048e+04,3.000000e+06,-0.180000,17.408508,12.932782,5449.473235,71.0
75%,27.270000,424.750000,26.000000,83.500000,523.000000,3.734761e+07,3.261378e+05,1.037500e+07,0.557500,60.119048,27.004160,14904.795767,88.75
max,67.390000,18266.000000,4223.000000,1069.000000,21914.000000,1.421022e+09,1.961210e+07,8.049000e+08,1.490000,233.103448,76.299320,82215.816862,99.0

In [96]:
#taux de la population mondiale représentée
total_population = df_final['Population'].sum()/8_000_000_000*100
print(total_population)

87.2308614375

In [97]:
# --- Export dataframe prêt pour analyse ---
df_final.to_csv("df_final_pour_analyse.csv", index=False, sep=';', decimal=',', encoding='utf-8-sig')

print("✅ Fichier exporté")

✅ Fichier exporté

<div style="background-color: RGB(150, 20, 30);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">FIN</h2>
</div>

In [98]:
print("FINI")

FINI